import {Router, type Request} from "express";
import {Timestamp} from "firebase-admin/firestore";
import {z} from "zod";
import {authenticate, requireRoles} from "./auth.js";
import {ApiError} from "./errors.js";
import {db} from "./firebase.js";

const router = Router();
const viewers = ["environmentalOfficer", "administrator", "superAdministrator"] as const;
function number(value: unknown) { return Number(value ?? 0); }
function range(request: Request) { const now = new Date(); const fallback = new Date(now.getTime() - 30 * 86400000); const from = request.query.from ? z.coerce.date().parse(request.query.from) : fallback; const to = request.query.to ? z.coerce.date().parse(request.query.to) : now; if (to <= from) throw new ApiError(400, "Analytics end must be after start.", "invalid_argument"); return {from, to, fromTimestamp: Timestamp.fromDate(from), toTimestamp: Timestamp.fromDate(to)}; }
async function dated(collection: string, request: Request, limit = 3000) { const period = range(request); const snapshot = await db.collection(collection).where("createdAt", ">=", period.fromTimestamp).where("createdAt", "<=", period.toTimestamp).limit(limit).get(); return {period, docs: snapshot.docs}; }
function day(value: unknown) { const date = (value as {toDate?: () => Date})?.toDate?.() ?? new Date(0); return date.toISOString().slice(0, 10); }

router.get("/analytics/overview", authenticate, requireRoles(...viewers), async (request, response) => { const [pickups, users, payments, batches, materials, partners] = await Promise.all([dated("pickupRequests", request), dated("users", request), dated("paymentTransactions", request), dated("recyclingBatches", request), dated("recoveredMaterialLots", request), dated("partners", request)]); const completed = pickups.docs.filter((doc) => ["completed", "collected", "received"].includes(String(doc.get("status")))); const collectedKg = completed.reduce((sum, doc) => sum + number(doc.get("actualWeight") ?? doc.get("estimatedWeight")), 0); const revenue = payments.docs.filter((doc) => ["confirmed", "partiallyRefunded"].includes(String(doc.get("status")))).reduce((sum, doc) => sum + number(doc.get("amount")) - number(doc.get("refundedAmount")), 0); response.json({data: {period: {from: pickups.period.from.toISOString(), to: pickups.period.to.toISOString()}, pickupRequests: pickups.docs.length, completedPickups: completed.length, pickupCompletionRate: pickups.docs.length ? completed.length / pickups.docs.length * 100 : 0, collectedKg, newUsers: users.docs.length, revenue, recyclingBatches: batches.docs.length, recoveredMaterialLots: materials.docs.length, newPartners: partners.docs.length}}); });

router.get("/analytics/collections/trends", authenticate, requireRoles(...viewers), async (request, response) => { const pickups = await dated("pickupRequests", request); const trend: Record<string, {requests: number; completed: number; weightKg: number}> = {}; for (const doc of pickups.docs) { const key = day(doc.get("createdAt")); trend[key] ??= {requests: 0, completed: 0, weightKg: 0}; trend[key].requests++; if (["completed", "collected", "received"].includes(String(doc.get("status")))) {trend[key].completed++; trend[key].weightKg += number(doc.get("actualWeight") ?? doc.get("estimatedWeight"));} } response.json({data: Object.entries(trend).sort(([a], [b]) => a.localeCompare(b)).map(([date, metrics]) => ({date, ...metrics}))}); });

router.get("/analytics/waste/categories", authenticate, requireRoles(...viewers), async (request, response) => { const pickups = await dated("pickupRequests", request); const categories: Record<string, {requests: number; quantity: number; weightKg: number}> = {}; for (const doc of pickups.docs) { const category = String(doc.get("category") ?? "other"); categories[category] ??= {requests: 0, quantity: 0, weightKg: 0}; categories[category].requests++; categories[category].quantity += number(doc.get("quantity")); categories[category].weightKg += number(doc.get("actualWeight") ?? doc.get("estimatedWeight")); } response.json({data: categories}); });

router.get("/analytics/waste/regions", authenticate, requireRoles(...viewers), async (request, response) => { const pickups = await dated("pickupRequests", request); const regions: Record<string, {requests: number; weightKg: number; completed: number}> = {}; for (const doc of pickups.docs) { const region = String(doc.get("serviceArea") ?? doc.get("location") ?? "Unspecified"); regions[region] ??= {requests: 0, weightKg: 0, completed: 0}; regions[region].requests++; regions[region].weightKg += number(doc.get("actualWeight") ?? doc.get("estimatedWeight")); if (["completed", "collected", "received"].includes(String(doc.get("status")))) regions[region].completed++; } response.json({data: regions}); });

router.get("/analytics/operations", authenticate, requireRoles(...viewers), async (request, response) => { const [schedules, centres, batches, materials] = await Promise.all([dated("collectionSchedules", request), db.collection("collectionCentres").limit(500).get(), dated("recyclingBatches", request), dated("recoveredMaterialLots", request)]); const completedSchedules = schedules.docs.filter((doc) => doc.get("status") === "completed"); const collectorPerformance: Record<string, {jobs: number; completed: number}> = {}; for (const doc of schedules.docs) for (const collector of doc.get("collectorIds") ?? []) { const key = String(collector); collectorPerformance[key] ??= {jobs: 0, completed: 0}; collectorPerformance[key].jobs++; if (doc.get("status") === "completed") collectorPerformance[key].completed++; } const centrePerformance = centres.docs.map((doc) => ({centreId: doc.id, name: doc.get("name"), currentStockKg: number(doc.get("currentStockKg")), capacityKg: number(doc.get("capacityKg")), utilizationPercent: number(doc.get("capacityKg")) ? number(doc.get("currentStockKg")) / number(doc.get("capacityKg")) * 100 : 0})); const inputWeight = batches.docs.reduce((sum, doc) => sum + number(doc.get("inputWeightKg")), 0); const recycledWeight = batches.docs.filter((doc) => doc.get("completionVerified") === true || doc.get("stage") === "completed").reduce((sum, doc) => sum + number(doc.get("inputWeightKg")), 0); const recoveredWeight = materials.docs.reduce((sum, doc) => sum + number(doc.get("weightKg")), 0); response.json({data: {pickupCompletionRate: schedules.docs.length ? completedSchedules.length / schedules.docs.length * 100 : 0, collectorPerformance, centrePerformance, recyclingRate: inputWeight ? recycledWeight / inputWeight * 100 : 0, resourceRecoveryRate: inputWeight ? recoveredWeight / inputWeight * 100 : 0}}); });

router.get("/analytics/revenue", authenticate, requireRoles(...viewers), async (request, response) => { const [payments, marketplace, recovery] = await Promise.all([dated("paymentTransactions", request), dated("marketplaceOrders", request), dated("recoveredMaterialLots", request)]); const byPurpose: Record<string, number> = {}; let paymentRevenue = 0; for (const doc of payments.docs) if (["confirmed", "partiallyRefunded"].includes(String(doc.get("status")))) { const value = number(doc.get("amount")) - number(doc.get("refundedAmount")); paymentRevenue += value; const purpose = String(doc.get("purpose") ?? "other"); byPurpose[purpose] = (byPurpose[purpose] ?? 0) + value; } const marketplaceRevenue = marketplace.docs.filter((doc) => doc.get("status") === "completed").reduce((sum, doc) => sum + number(doc.get("total")), 0); const materialRevenue = recovery.docs.reduce((sum, doc) => sum + number(doc.get("saleRevenue")), 0); response.json({data: {paymentRevenue, marketplaceRevenue, materialRevenue, combinedRevenue: paymentRevenue + marketplaceRevenue + materialRevenue, byPurpose}}); });

router.get("/analytics/users/growth", authenticate, requireRoles(...viewers), async (request, response) => { const usersSnapshot = await dated("users", request); const growth: Record<string, Record<string, number>> = {}; for (const doc of usersSnapshot.docs) { const date = day(doc.get("createdAt")); const role = String(doc.get("role") ?? "unknown"); growth[date] ??= {}; growth[date][role] = (growth[date][role] ?? 0) + 1; } response.json({data: Object.entries(growth).sort(([a], [b]) => a.localeCompare(b)).map(([date, roles]) => ({date, roles, total: Object.values(roles).reduce((sum, value) => sum + value, 0)}))}); });

router.get("/analytics/partners/performance", authenticate, requireRoles(...viewers), async (_request, response) => { const partners = await db.collection("partners").limit(1000).get(); response.json({data: partners.docs.map((doc) => ({partnerId: doc.id, name: doc.get("name"), status: doc.get("status"), serviceCategories: doc.get("serviceCategories") ?? [], capacityKg: number(doc.get("facilityCapacityKg")), performanceRating: number(doc.get("performanceRating")), complianceScore: number(doc.get("complianceScore")), activeContracts: number(doc.get("activeContractCount"))})).sort((a, b) => b.performanceRating - a.performanceRating)}); });

router.get("/analytics/environmental", authenticate, requireRoles(...viewers), async (request, response) => { const [pickups, batches, materials, hazardous, repairs, formulas] = await Promise.all([dated("pickupRequests", request), dated("recyclingBatches", request), dated("recoveredMaterialLots", request), dated("hazardousWasteRecords", request), dated("repairJobs", request), db.collection("systemSettings").doc("environmentalFormulas").get()]); const collectedKg = pickups.docs.filter((doc) => ["completed", "collected", "received"].includes(String(doc.get("status")))).reduce((sum, doc) => sum + number(doc.get("actualWeight") ?? doc.get("estimatedWeight")), 0); const recycledKg = batches.docs.filter((doc) => doc.get("completionVerified") === true || doc.get("stage") === "completed").reduce((sum, doc) => sum + number(doc.get("inputWeightKg")), 0); const recoveredKg = materials.docs.reduce((sum, doc) => sum + number(doc.get("weightKg")), 0); const hazardousKg = hazardous.docs.reduce((sum, doc) => sum + number(doc.get("disposedWeightKg")), 0); const reusableDevices = repairs.docs.filter((doc) => doc.get("status") === "completed").length; const carbonRate = number(formulas.get("carbonAvoidedKgPerRecycledKg") || 1.85); const energyRate = number(formulas.get("energySavedKwhPerRecycledKg") || 2.4); response.json({data: {collectedKg, recycledKg, recoveredKg, hazardousKg, reusableDevices, landfillDiversionRate: collectedKg ? Math.min(100, recycledKg / collectedKg * 100) : 0, carbonAvoidedKg: recycledKg * carbonRate, energySavedKwh: recycledKg * energyRate}}); });

router.get("/analytics/widgets", authenticate, requireRoles(...viewers), async (request, response) => { const snapshot = await db.collection("dashboardWidgets").where("active", "==", true).limit(100).get(); const role = request.user!.role; const widgets = snapshot.docs.filter((doc) => !(doc.get("roles") ?? []).length || (doc.get("roles") ?? []).includes(role)).map((doc) => ({id: doc.id, data: doc.data(), order: number(doc.get("order"))})).sort((a, b) => a.order - b.order).map((widget) => ({id: widget.id, ...widget.data})); response.json({data: widgets}); });

router.put("/analytics/widgets/:id", authenticate, requireRoles(...viewers), async (request, response) => { const input = z.object({title: z.string().trim().min(2).max(200), metric: z.enum(["collections", "weight", "recyclingRate", "recoveryRate", "revenue", "users", "partners", "environmentalImpact"]), visualization: z.enum(["number", "line", "bar", "pie", "table", "map"]), roles: z.array(z.string().trim().min(1)).default([]), order: z.number().int().nonnegative(), active: z.boolean()}).parse(request.body); const widgetId = Array.isArray(request.params.id) ? request.params.id[0] : request.params.id; await db.collection("dashboardWidgets").doc(widgetId).set({...input, updatedBy: request.user!.uid, updatedAt: Timestamp.now()}, {merge: true}); response.json({data: {id: widgetId}}); });

router.post("/analytics/exports", authenticate, requireRoles(...viewers), async (request, response) => { const input = z.object({dataset: z.enum(["overview", "collectionTrends", "wasteCategories", "regions", "operations", "revenue", "userGrowth", "partnerPerformance", "environmentalImpact"]), format: z.enum(["pdf", "csv", "xlsx"]), from: z.coerce.date(), to: z.coerce.date()}).parse(request.body); if (input.to <= input.from) throw new ApiError(400, "Export end must be after start.", "invalid_argument"); const ref = db.collection("analyticsExports").doc(); await ref.set({...input, status: "queued", requestedBy: request.user!.uid, requestedAt: Timestamp.now()}); response.status(202).json({data: {id: ref.id, status: "queued", downloadUrl: null}}); });

export default router;
