import {Router} from "express";
import {FieldValue, Timestamp} from "firebase-admin/firestore";
import {z} from "zod";
import {authenticate, requireRoles} from "./auth.js";
import {ApiError} from "./errors.js";
import {db} from "./firebase.js";
import {documentJson} from "./firestore-json.js";

const router = Router(); const users = ["household", "business", "institution", "collector", "driver", "collectionCentreOperator", "repairTechnician", "recycler", "environmentalOfficer", "administrator", "superAdministrator"] as const; const managers = ["environmentalOfficer", "administrator", "superAdministrator"] as const;
const channels = ["push", "sms", "email", "inApp"] as const; const categories = ["pickupReminder", "assignment", "statusUpdate", "payment", "reward", "compliance", "maintenance", "emergency", "general"] as const;
function id(value: string | string[]) { return Array.isArray(value) ? value[0] : value; }

router.get("/communication/preferences", authenticate, requireRoles(...users), async (request, response) => { const snapshot = await db.collection("notificationPreferences").doc(request.user!.uid).get(); response.json({data: snapshot.exists ? documentJson(snapshot.id, snapshot.data()!) : {id: request.user!.uid, channels: {push: true, sms: false, email: true, inApp: true}, categories: Object.fromEntries(categories.map((category) => [category, true])), quietHours: null}}); });
router.put("/communication/preferences", authenticate, requireRoles(...users), async (request, response) => { const input = z.object({channels: z.object({push: z.boolean(), sms: z.boolean(), email: z.boolean(), inApp: z.boolean()}), categories: z.record(z.enum(categories), z.boolean()), quietHours: z.object({enabled: z.boolean(), start: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), end: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), timezone: z.string().trim().min(2).max(100)}).nullable()}).parse(request.body); await db.collection("notificationPreferences").doc(request.user!.uid).set({...input, userId: request.user!.uid, updatedAt: FieldValue.serverTimestamp()}, {merge: true}); response.json({data: {id: request.user!.uid}}); });

router.get("/communication/templates", authenticate, requireRoles(...managers), async (request, response) => { let query: FirebaseFirestore.Query = db.collection("notificationTemplates"); if (typeof request.query.category === "string") query = query.where("category", "==", request.query.category); const snapshot = await query.limit(300).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.put("/communication/templates/:id", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({name: z.string().trim().min(2).max(200), category: z.enum(categories), channel: z.enum(channels), subject: z.string().trim().max(300).default(""), body: z.string().trim().min(2).max(5000), variables: z.array(z.string().trim().min(1).max(100)).default([]), active: z.boolean()}).parse(request.body); const templateId = id(request.params.id); await db.collection("notificationTemplates").doc(templateId).set({...input, updatedBy: request.user!.uid, updatedAt: FieldValue.serverTimestamp()}, {merge: true}); response.json({data: {id: templateId}}); });

router.post("/communication/send", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({recipientIds: z.array(z.string().trim().min(1)).min(1).max(1000), category: z.enum(categories), channels: z.array(z.enum(channels)).min(1), templateId: z.string().trim().max(200).default(""), title: z.string().trim().min(2).max(300), body: z.string().trim().min(2).max(5000), data: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])).default({}), scheduledAt: z.coerce.date().nullable().default(null), priority: z.enum(["normal", "high", "critical"]).default("normal")}).parse(request.body); if (input.category === "emergency" && input.priority !== "critical") throw new ApiError(400, "Emergency notifications must be critical.", "invalid_argument"); const batch = db.batch(); const ids: string[] = []; for (const recipientId of input.recipientIds) { const outbox = db.collection("notificationOutbox").doc(); ids.push(outbox.id); batch.set(outbox, {...input, recipientId, scheduledAt: input.scheduledAt ? Timestamp.fromDate(input.scheduledAt) : null, status: input.scheduledAt && input.scheduledAt > new Date() ? "scheduled" : "queued", createdBy: request.user!.uid, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); batch.set(db.collection("users").doc(recipientId).collection("notifications").doc(outbox.id), {title: input.title, body: input.body, type: input.category, data: input.data, read: false, status: "queued", createdAt: FieldValue.serverTimestamp()}); } await batch.commit(); response.status(202).json({data: {notificationIds: ids, recipients: input.recipientIds.length, status: "queued"}}); });

router.get("/communication/notifications", authenticate, requireRoles(...users), async (request, response) => { const limit = z.coerce.number().int().min(1).max(500).default(100).parse(request.query.limit); const snapshot = await db.collection("users").doc(request.user!.uid).collection("notifications").orderBy("createdAt", "desc").limit(limit).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.patch("/communication/notifications/:id/read", authenticate, requireRoles(...users), async (request, response) => { const ref = db.collection("users").doc(request.user!.uid).collection("notifications").doc(id(request.params.id)); const snapshot = await ref.get(); if (!snapshot.exists) throw new ApiError(404, "Notification not found.", "not_found"); await ref.update({read: true, readAt: FieldValue.serverTimestamp()}); response.json({data: {id: ref.id, read: true}}); });

router.post("/communication/conversations", authenticate, requireRoles(...users), async (request, response) => { const input = z.object({participantIds: z.array(z.string().trim().min(1)).min(1).max(20), subject: z.string().trim().min(2).max(300), initialMessage: z.string().trim().min(1).max(5000)}).parse(request.body); const participants = [...new Set([request.user!.uid, ...input.participantIds])]; const ref = db.collection("conversations").doc(); const message = ref.collection("messages").doc(); const batch = db.batch(); batch.set(ref, {subject: input.subject, participantIds: participants, lastMessage: input.initialMessage, lastMessageAt: FieldValue.serverTimestamp(), createdBy: request.user!.uid, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); batch.set(message, {senderId: request.user!.uid, body: input.initialMessage, attachmentUrls: [], createdAt: FieldValue.serverTimestamp()}); await batch.commit(); response.status(201).json({data: {id: ref.id}}); });
router.get("/communication/conversations", authenticate, requireRoles(...users), async (request, response) => { const snapshot = await db.collection("conversations").where("participantIds", "array-contains", request.user!.uid).limit(200).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.post("/communication/conversations/:id/messages", authenticate, requireRoles(...users), async (request, response) => { const input = z.object({body: z.string().trim().min(1).max(5000), attachmentUrls: z.array(z.string().url()).max(10).default([])}).parse(request.body); const conversation = db.collection("conversations").doc(id(request.params.id)); const snapshot = await conversation.get(); if (!snapshot.exists) throw new ApiError(404, "Conversation not found.", "not_found"); if (!(snapshot.get("participantIds") ?? []).includes(request.user!.uid)) throw new ApiError(403, "You are not a conversation participant.", "forbidden"); const ref = conversation.collection("messages").doc(); const batch = db.batch(); batch.set(ref, {...input, senderId: request.user!.uid, createdAt: FieldValue.serverTimestamp()}); batch.update(conversation, {lastMessage: input.body, lastMessageAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); await batch.commit(); response.status(201).json({data: {id: ref.id}}); });
router.get("/communication/conversations/:id/messages", authenticate, requireRoles(...users), async (request, response) => { const conversation = db.collection("conversations").doc(id(request.params.id)); const current = await conversation.get(); if (!current.exists) throw new ApiError(404, "Conversation not found.", "not_found"); if (!(current.get("participantIds") ?? []).includes(request.user!.uid)) throw new ApiError(403, "You are not a conversation participant.", "forbidden"); const snapshot = await conversation.collection("messages").orderBy("createdAt", "asc").limit(500).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.get("/communication/reports/summary", authenticate, requireRoles(...managers), async (_request, response) => { const [outbox, templates, preferences] = await Promise.all([db.collection("notificationOutbox").limit(2000).get(), db.collection("notificationTemplates").limit(500).get(), db.collection("notificationPreferences").limit(2000).get()]); const byStatus: Record<string, number> = {}; const byCategory: Record<string, number> = {}; for (const doc of outbox.docs) { const status = String(doc.get("status") ?? "unknown"); const category = String(doc.get("category") ?? "general"); byStatus[status] = (byStatus[status] ?? 0) + 1; byCategory[category] = (byCategory[category] ?? 0) + 1; } response.json({data: {messages: outbox.size, templates: templates.size, preferenceProfiles: preferences.size, byStatus, byCategory}}); });

export default router;
