import {Router} from "express";
import {FieldValue, Timestamp} from "firebase-admin/firestore";
import {z} from "zod";
import {authenticate, requireRoles} from "./auth.js";
import {ApiError} from "./errors.js";
import {db} from "./firebase.js";
import {documentJson} from "./firestore-json.js";

const router = Router();
const applicants = ["household", "business", "institution", "collector", "driver", "collectionCentreOperator", "repairTechnician", "recycler", "environmentalOfficer", "administrator", "superAdministrator"] as const;
const managers = ["environmentalOfficer", "administrator", "superAdministrator"] as const;
const operators = ["repairTechnician", "environmentalOfficer", "administrator", "superAdministrator"] as const;

function id(value: string | string[]) { return Array.isArray(value) ? value[0] : value; }
function number(value: unknown) { return Number(value ?? 0); }
async function beneficiaryRecord(beneficiaryId: string) { const ref = db.collection("donationBeneficiaries").doc(beneficiaryId); const snapshot = await ref.get(); if (!snapshot.exists) throw new ApiError(404, "Beneficiary not found.", "not_found"); return {ref, snapshot}; }
async function requestRecord(requestId: string) { const ref = db.collection("donationRequests").doc(requestId); const snapshot = await ref.get(); if (!snapshot.exists) throw new ApiError(404, "Donation request not found.", "not_found"); return {ref, snapshot}; }
function requestAccess(data: FirebaseFirestore.DocumentData, uid: string, role: string) { return ["repairTechnician", "environmentalOfficer", "administrator", "superAdministrator"].includes(role) || data.requestedBy === uid || data.beneficiaryUserId === uid; }

router.post("/donations/beneficiaries", authenticate, requireRoles(...applicants), async (request, response) => {
  const input = z.object({type: z.enum(["school", "community", "nonprofit", "healthFacility", "governmentInstitution", "other"]), name: z.string().trim().min(2).max(300), registrationNumber: z.string().trim().max(150).default(""), contactName: z.string().trim().min(2).max(200), contactEmail: z.string().trim().email(), contactPhone: z.string().trim().min(5).max(50), address: z.string().trim().min(2).max(500), district: z.string().trim().min(2).max(100), beneficiariesServed: z.number().int().positive(), mission: z.string().trim().min(2).max(2000), verificationDocumentUrls: z.array(z.string().url()).min(1).max(10)}).parse(request.body);
  const ref = db.collection("donationBeneficiaries").doc(); await ref.set({...input, beneficiaryCode: `BEN-${ref.id.substring(0, 8).toUpperCase()}`, userId: request.user!.uid, eligibilityStatus: "pending", active: true, totalDevicesReceived: 0, createdBy: request.user!.uid, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()});
  response.status(201).json({data: {id: ref.id, beneficiaryCode: `BEN-${ref.id.substring(0, 8).toUpperCase()}`}});
});

router.get("/donations/beneficiaries", authenticate, requireRoles(...operators), async (request, response) => {
  let query: FirebaseFirestore.Query = db.collection("donationBeneficiaries"); if (typeof request.query.eligibilityStatus === "string") query = query.where("eligibilityStatus", "==", request.query.eligibilityStatus); const snapshot = await query.limit(500).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))});
});

router.get("/donations/beneficiaries/:id", authenticate, requireRoles(...applicants), async (request, response) => {
  const beneficiary = await beneficiaryRecord(id(request.params.id)); if (beneficiary.snapshot.get("userId") !== request.user!.uid && !["repairTechnician", "environmentalOfficer", "administrator", "superAdministrator"].includes(request.user!.role)) throw new ApiError(403, "You cannot access this beneficiary.", "forbidden"); response.json({data: documentJson(beneficiary.snapshot.id, beneficiary.snapshot.data()!)});
});

router.patch("/donations/beneficiaries/:id/eligibility", authenticate, requireRoles(...managers), async (request, response) => {
  const input = z.object({decision: z.enum(["eligible", "ineligible", "needsInformation"]), score: z.number().min(0).max(100), criteria: z.record(z.string(), z.boolean()), notes: z.string().trim().max(2000).default("")}).parse(request.body); const beneficiary = await beneficiaryRecord(id(request.params.id)); await beneficiary.ref.update({eligibilityStatus: input.decision, eligibilityScore: input.score, eligibilityCriteria: input.criteria, eligibilityNotes: input.notes, assessedBy: request.user!.uid, assessedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: beneficiary.ref.id, eligibilityStatus: input.decision}});
});

router.post("/donations/requests", authenticate, requireRoles(...applicants), async (request, response) => {
  const input = z.object({beneficiaryId: z.string().trim().min(1), deviceCategory: z.string().trim().min(2).max(100), quantity: z.number().int().positive().max(1000), purpose: z.string().trim().min(2).max(2000), urgency: z.enum(["normal", "high", "critical"]), requestedDeliveryDate: z.coerce.date(), supportingDocumentUrls: z.array(z.string().url()).max(10).default([])}).parse(request.body); const beneficiary = await beneficiaryRecord(input.beneficiaryId); if (beneficiary.snapshot.get("userId") !== request.user!.uid && !["administrator", "superAdministrator"].includes(request.user!.role)) throw new ApiError(403, "You cannot request on behalf of this beneficiary.", "forbidden");
  const ref = db.collection("donationRequests").doc(); await ref.set({...input, requestCode: `DON-${ref.id.substring(0, 8).toUpperCase()}`, beneficiaryName: beneficiary.snapshot.get("name"), beneficiaryUserId: beneficiary.snapshot.get("userId"), requestedDeliveryDate: Timestamp.fromDate(input.requestedDeliveryDate), allocatedDeviceIds: [], allocatedQuantity: 0, status: "submitted", requestedBy: request.user!.uid, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.status(201).json({data: {id: ref.id, requestCode: `DON-${ref.id.substring(0, 8).toUpperCase()}`}});
});

router.get("/donations/requests", authenticate, requireRoles(...applicants), async (request, response) => {
  const privileged = ["repairTechnician", "environmentalOfficer", "administrator", "superAdministrator"].includes(request.user!.role); let query: FirebaseFirestore.Query = db.collection("donationRequests"); if (!privileged) query = query.where("requestedBy", "==", request.user!.uid); if (typeof request.query.status === "string") query = query.where("status", "==", request.query.status); const snapshot = await query.limit(500).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))});
});

router.get("/donations/requests/:id", authenticate, requireRoles(...applicants), async (request, response) => { const donation = await requestRecord(id(request.params.id)); if (!requestAccess(donation.snapshot.data()!, request.user!.uid, request.user!.role)) throw new ApiError(403, "You cannot access this donation request.", "forbidden"); response.json({data: documentJson(donation.snapshot.id, donation.snapshot.data()!)}); });

router.patch("/donations/requests/:id/review", authenticate, requireRoles(...managers), async (request, response) => {
  const input = z.object({decision: z.enum(["approved", "rejected"]), notes: z.string().trim().max(2000).default("")}).parse(request.body); const donation = await requestRecord(id(request.params.id)); if (donation.snapshot.get("status") !== "submitted") throw new ApiError(409, "Only submitted requests can be reviewed.", "invalid_state"); const beneficiary = await beneficiaryRecord(String(donation.snapshot.get("beneficiaryId"))); if (input.decision === "approved" && beneficiary.snapshot.get("eligibilityStatus") !== "eligible") throw new ApiError(409, "The beneficiary must be eligible before approval.", "beneficiary_not_eligible"); await donation.ref.update({status: input.decision, reviewNotes: input.notes, reviewedBy: request.user!.uid, reviewedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: donation.ref.id, status: input.decision}});
});

router.patch("/donations/requests/:id/allocation", authenticate, requireRoles(...operators), async (request, response) => {
  const input = z.object({deviceIds: z.array(z.string().trim().min(1)).min(1)}).parse(request.body); const donation = await requestRecord(id(request.params.id)); if (donation.snapshot.get("status") !== "approved") throw new ApiError(409, "Only approved requests can receive devices.", "invalid_state"); if (input.deviceIds.length > number(donation.snapshot.get("quantity"))) throw new ApiError(409, "Allocated quantity exceeds the request.", "quantity_exceeded");
  const deviceRefs = input.deviceIds.map((deviceId) => db.collection("refurbishedInventory").doc(deviceId)); const devices = await Promise.all(deviceRefs.map((ref) => ref.get())); if (devices.some((device) => !device.exists || !["available", "donationApproved"].includes(String(device.get("status"))))) throw new ApiError(409, "Every device must be available for donation.", "device_unavailable"); const batch = db.batch(); batch.update(donation.ref, {allocatedDeviceIds: input.deviceIds, allocatedQuantity: input.deviceIds.length, status: "allocated", allocatedBy: request.user!.uid, allocatedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); for (const ref of deviceRefs) batch.update(ref, {status: "allocatedForDonation", donationRequestId: donation.ref.id, updatedAt: FieldValue.serverTimestamp()}); await batch.commit(); response.json({data: {id: donation.ref.id, status: "allocated", allocatedQuantity: input.deviceIds.length}});
});

router.patch("/donations/requests/:id/delivery", authenticate, requireRoles(...operators), async (request, response) => {
  const input = z.object({status: z.enum(["scheduled", "dispatched", "delivered"]), scheduledAt: z.coerce.date(), carrier: z.string().trim().min(2).max(200), trackingReference: z.string().trim().min(1).max(200), proofOfDeliveryUrls: z.array(z.string().url()).max(10).default([]), recipientName: z.string().trim().max(200).default("")}).parse(request.body); const donation = await requestRecord(id(request.params.id)); if (!["allocated", "deliveryScheduled", "dispatched"].includes(String(donation.snapshot.get("status")))) throw new ApiError(409, "The donation is not ready for this delivery update.", "invalid_state"); if (input.status === "delivered" && (!input.proofOfDeliveryUrls.length || !input.recipientName)) throw new ApiError(400, "Delivery proof and recipient name are required.", "invalid_argument"); const status = input.status === "scheduled" ? "deliveryScheduled" : input.status; await donation.ref.update({...input, scheduledAt: Timestamp.fromDate(input.scheduledAt), status, deliveryUpdatedBy: request.user!.uid, deliveryUpdatedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: donation.ref.id, status}});
});

router.patch("/donations/requests/:id/confirm", authenticate, requireRoles(...applicants), async (request, response) => {
  const input = z.object({confirmed: z.literal(true), condition: z.enum(["excellent", "good", "acceptable", "damaged"]), comments: z.string().trim().max(1000).default("")}).parse(request.body); const donation = await requestRecord(id(request.params.id)); if (donation.snapshot.get("beneficiaryUserId") !== request.user!.uid) throw new ApiError(403, "Only the beneficiary can confirm delivery.", "forbidden"); if (donation.snapshot.get("status") !== "delivered") throw new ApiError(409, "The donation has not been delivered.", "invalid_state"); const beneficiary = db.collection("donationBeneficiaries").doc(String(donation.snapshot.get("beneficiaryId"))); const batch = db.batch(); batch.update(donation.ref, {...input, status: "confirmed", confirmedBy: request.user!.uid, confirmedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); batch.update(beneficiary, {totalDevicesReceived: FieldValue.increment(number(donation.snapshot.get("allocatedQuantity"))), updatedAt: FieldValue.serverTimestamp()}); for (const deviceId of donation.snapshot.get("allocatedDeviceIds") ?? []) batch.update(db.collection("refurbishedInventory").doc(String(deviceId)), {status: "donated", donatedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); await batch.commit(); response.json({data: {id: donation.ref.id, status: "confirmed"}});
});

router.post("/donations/requests/:id/follow-ups", authenticate, requireRoles(...operators), async (request, response) => {
  const input = z.object({devicesInUse: z.number().int().nonnegative(), devicesFunctional: z.number().int().nonnegative(), peopleReached: z.number().int().nonnegative(), usageSummary: z.string().trim().min(2).max(2000), issues: z.array(z.string().trim().min(2).max(500)).default([]), evidenceUrls: z.array(z.string().url()).max(10).default([])}).refine((value) => value.devicesFunctional <= value.devicesInUse, "Functional devices cannot exceed devices in use.").parse(request.body); const donation = await requestRecord(id(request.params.id)); if (donation.snapshot.get("status") !== "confirmed") throw new ApiError(409, "Follow-up requires a confirmed donation.", "invalid_state"); const ref = await donation.ref.collection("followUps").add({...input, recordedBy: request.user!.uid, createdAt: FieldValue.serverTimestamp()}); await donation.ref.update({latestPeopleReached: input.peopleReached, latestDevicesFunctional: input.devicesFunctional, lastFollowUpAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.status(201).json({data: {id: ref.id}});
});

router.get("/donations/requests/:id/history", authenticate, requireRoles(...applicants), async (request, response) => { const donation = await requestRecord(id(request.params.id)); if (!requestAccess(donation.snapshot.data()!, request.user!.uid, request.user!.role)) throw new ApiError(403, "You cannot access this donation history.", "forbidden"); const followUps = await donation.ref.collection("followUps").orderBy("createdAt", "desc").limit(100).get(); response.json({data: {request: documentJson(donation.snapshot.id, donation.snapshot.data()!), followUps: followUps.docs.map((doc) => documentJson(doc.id, doc.data()))}}); });

router.get("/donations/requests/:id/certificate", authenticate, requireRoles(...applicants), async (request, response) => { const donation = await requestRecord(id(request.params.id)); if (!requestAccess(donation.snapshot.data()!, request.user!.uid, request.user!.role)) throw new ApiError(403, "You cannot access this certificate.", "forbidden"); if (donation.snapshot.get("status") !== "confirmed") throw new ApiError(409, "A certificate is available after beneficiary confirmation.", "invalid_state"); response.json({data: {certificateNumber: `DON-CERT-${donation.ref.id.substring(0, 10).toUpperCase()}`, issuedAt: new Date().toISOString(), beneficiaryName: donation.snapshot.get("beneficiaryName"), deviceCategory: donation.snapshot.get("deviceCategory"), donatedQuantity: donation.snapshot.get("allocatedQuantity"), requestId: donation.ref.id}}); });

router.get("/donations/reports/impact", authenticate, requireRoles(...managers), async (_request, response) => { const [requests, beneficiaries] = await Promise.all([db.collection("donationRequests").limit(1000).get(), db.collection("donationBeneficiaries").limit(1000).get()]); const byStatus: Record<string, number> = {}; const byCategory: Record<string, number> = {}; let devicesDonated = 0; let peopleReached = 0; for (const doc of requests.docs) { const status = String(doc.get("status") ?? "unknown"); const category = String(doc.get("deviceCategory") ?? "unknown"); byStatus[status] = (byStatus[status] ?? 0) + 1; byCategory[category] = (byCategory[category] ?? 0) + number(doc.get("allocatedQuantity")); if (status === "confirmed") devicesDonated += number(doc.get("allocatedQuantity")); peopleReached += number(doc.get("latestPeopleReached")); } response.json({data: {totalRequests: requests.size, registeredBeneficiaries: beneficiaries.size, eligibleBeneficiaries: beneficiaries.docs.filter((doc) => doc.get("eligibilityStatus") === "eligible").length, devicesDonated, peopleReached, byStatus, byCategory}}); });

export default router;
