import {Router, type Request} from "express";
import {FieldValue, Timestamp} from "firebase-admin/firestore";
import {z} from "zod";
import {authenticate, requireRoles} from "./auth.js";
import {ApiError} from "./errors.js";
import {db} from "./firebase.js";
import {documentJson} from "./firestore-json.js";

const router = Router();
const users = ["household", "business", "institution", "collector", "driver", "collectionCentreOperator", "repairTechnician", "recycler", "environmentalOfficer", "administrator", "superAdministrator"] as const;
const managers = ["environmentalOfficer", "administrator", "superAdministrator"] as const;
const defaultFormulas = {carbonAvoidedKgPerRecycledKg: 1.85, energySavedKwhPerRecycledKg: 2.4, treesPerTonneCarbon: 45, waterProtectedLitresPerHazardousKg: 500, landfillDiversionIncludesReuse: true};
function number(value: unknown) { return Number(value ?? 0); }
function scope(request: Request) { const requested = typeof request.query.userId === "string" ? request.query.userId : ""; const privileged = ["environmentalOfficer", "administrator", "superAdministrator"].includes(request.user!.role); if (requested && requested !== request.user!.uid && !privileged) throw new ApiError(403, "You cannot access another user's impact.", "forbidden"); return requested || (privileged ? "" : request.user!.uid); }
async function formulas() { const snapshot = await db.collection("systemSettings").doc("environmentalFormulas").get(); return {...defaultFormulas, ...(snapshot.exists ? snapshot.data() : {})}; }
async function calculate(userId = "") {
  let pickupsQuery: FirebaseFirestore.Query = db.collection("pickupRequests"); if (userId) pickupsQuery = pickupsQuery.where("userId", "==", userId);
  const [pickups, batches, materials, hazardous, repairs, formula] = await Promise.all([pickupsQuery.limit(2000).get(), db.collection("recyclingBatches").limit(1000).get(), db.collection("recoveredMaterialLots").limit(2000).get(), db.collection("hazardousWasteRecords").limit(1000).get(), db.collection("repairJobs").limit(1000).get(), formulas()]);
  const completedPickups = pickups.docs.filter((doc) => ["completed", "collected", "received"].includes(String(doc.get("status")))); const totalCollectedKg = completedPickups.reduce((sum, doc) => sum + number(doc.get("actualWeight") ?? doc.get("estimatedWeight")), 0); const totalRecycledKg = batches.docs.filter((doc) => doc.get("completionVerified") === true || doc.get("stage") === "completed").reduce((sum, doc) => sum + number(doc.get("inputWeightKg")), 0); const materialsRecoveredKg = materials.docs.reduce((sum, doc) => sum + number(doc.get("weightKg")), 0); const hazardousSafelyHandledKg = hazardous.docs.reduce((sum, doc) => sum + number(doc.get("disposedWeightKg")), 0); const reusableDevicesRecovered = repairs.docs.filter((doc) => doc.get("status") === "completed").length; const reusedEstimatedKg = repairs.docs.filter((doc) => doc.get("status") === "completed").reduce((sum, doc) => sum + number(doc.get("weightKg")), 0); const divertedKg = totalRecycledKg + (formula.landfillDiversionIncludesReuse ? reusedEstimatedKg : 0); const landfillDiversionRate = totalCollectedKg ? Math.min(100, divertedKg / totalCollectedKg * 100) : 0; const carbonEmissionsAvoidedKg = totalRecycledKg * number(formula.carbonAvoidedKgPerRecycledKg); const energySavedKwh = totalRecycledKg * number(formula.energySavedKwhPerRecycledKg); const treesEquivalent = carbonEmissionsAvoidedKg / 1000 * number(formula.treesPerTonneCarbon); const waterPollutionReductionLitres = hazardousSafelyHandledKg * number(formula.waterProtectedLitresPerHazardousKg); return {totalCollectedKg, totalRecycledKg, landfillDiversionRate, materialsRecoveredKg, carbonEmissionsAvoidedKg, energySavedKwh, hazardousSafelyHandledKg, reusableDevicesRecovered, treesEquivalent, waterPollutionReductionLitres, formulas: formula};
}

router.get("/impact/summary", authenticate, requireRoles(...users), async (request, response) => { response.json({data: await calculate(scope(request))}); });

router.get("/impact/formulas", authenticate, requireRoles(...users), async (_request, response) => { response.json({data: await formulas()}); });

router.put("/impact/formulas", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({carbonAvoidedKgPerRecycledKg: z.number().nonnegative(), energySavedKwhPerRecycledKg: z.number().nonnegative(), treesPerTonneCarbon: z.number().nonnegative(), waterProtectedLitresPerHazardousKg: z.number().nonnegative(), landfillDiversionIncludesReuse: z.boolean()}).parse(request.body); await db.collection("systemSettings").doc("environmentalFormulas").set({...input, updatedBy: request.user!.uid, updatedAt: FieldValue.serverTimestamp()}); response.json({data: input}); });

router.post("/impact/snapshots", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({period: z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/), notes: z.string().trim().max(1000).default("")}).parse(request.body); const metrics = await calculate(); const ref = db.collection("environmentalImpactSnapshots").doc(input.period); await ref.set({...input, ...metrics, generatedBy: request.user!.uid, generatedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}, {merge: true}); response.status(201).json({data: {id: ref.id, ...metrics}}); });

router.get("/impact/monthly", authenticate, requireRoles(...users), async (request, response) => { const months = z.coerce.number().int().min(1).max(60).default(12).parse(request.query.months); const snapshot = await db.collection("environmentalImpactSnapshots").orderBy("period", "desc").limit(months).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });

router.get("/impact/comparison", authenticate, requireRoles(...users), async (request, response) => { const from = z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/).parse(request.query.from); const to = z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/).parse(request.query.to); const [first, second] = await Promise.all([db.collection("environmentalImpactSnapshots").doc(from).get(), db.collection("environmentalImpactSnapshots").doc(to).get()]); if (!first.exists || !second.exists) throw new ApiError(404, "Both monthly impact snapshots are required.", "not_found"); const fields = ["totalCollectedKg", "totalRecycledKg", "landfillDiversionRate", "materialsRecoveredKg", "carbonEmissionsAvoidedKg", "energySavedKwh", "hazardousSafelyHandledKg", "reusableDevicesRecovered", "treesEquivalent", "waterPollutionReductionLitres"]; const changes: Record<string, {from: number; to: number; change: number; percent: number}> = {}; for (const field of fields) { const a = number(first.get(field)); const b = number(second.get(field)); changes[field] = {from: a, to: b, change: b - a, percent: a ? (b - a) / a * 100 : b ? 100 : 0}; } response.json({data: {from, to, changes}}); });

router.post("/impact/adjustments", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({metric: z.enum(["totalCollectedKg", "totalRecycledKg", "materialsRecoveredKg", "carbonEmissionsAvoidedKg", "energySavedKwh", "hazardousSafelyHandledKg", "reusableDevicesRecovered", "treesEquivalent", "waterPollutionReductionLitres"]), value: z.number(), reason: z.string().trim().min(2).max(1000), referenceId: z.string().trim().min(1).max(200)}).parse(request.body); const ref = await db.collection("environmentalImpactAdjustments").add({...input, approvedBy: request.user!.uid, createdAt: FieldValue.serverTimestamp()}); response.status(201).json({data: {id: ref.id}}); });

router.get("/impact/report", authenticate, requireRoles(...users), async (request, response) => { const metrics = await calculate(scope(request)); const snapshots = await db.collection("environmentalImpactSnapshots").orderBy("period", "desc").limit(12).get(); response.json({data: {reportNumber: `ENV-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}`, generatedAt: new Date().toISOString(), generatedForUserId: scope(request) || "platform", metrics, monthlyTrend: snapshots.docs.map((doc) => documentJson(doc.id, doc.data()))}}); });

export default router;
