export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "EcoTrace API",
    version: "1.0.0",
    description: "Versioned API for EcoTrace e-waste collection and processing workflows.",
  },
  servers: [{url: "/api/v1", description: "Current deployment"}],
  components: {
    securitySchemes: {
      firebaseAuth: {type: "http", scheme: "bearer", bearerFormat: "Firebase ID token"},
    },
  },
  paths: {
    "/me": {get: {security: [{firebaseAuth: []}], summary: "Return the authenticated user profile", responses: {"200": {description: "Current user"}}}},
    "/admin/demo-data": {post: {security: [{firebaseAuth: []}], summary: "Create deterministic dashboard demo records", responses: {"200": {description: "Demo records created or refreshed"}}}},
    "/collection-centres": {
      get: {summary: "List the public collection-centre directory", responses: {"200": {description: "Active centres"}}},
      post: {security: [{firebaseAuth: []}], summary: "Register a collection centre", responses: {"201": {description: "Centre created"}}},
    },
    "/vehicles": {
      get: {security: [{firebaseAuth: []}], summary: "List vehicles", responses: {"200": {description: "Vehicles"}}},
      post: {security: [{firebaseAuth: []}], summary: "Register a vehicle", responses: {"201": {description: "Vehicle created"}}},
    },
    "/pickup-requests": {
      get: {security: [{firebaseAuth: []}], summary: "List accessible pickup requests", responses: {"200": {description: "Pickup requests"}}},
      post: {security: [{firebaseAuth: []}], summary: "Submit a pickup request", responses: {"201": {description: "Pickup created"}}},
    },
    "/pickup-requests/{id}/cancel": {patch: {security: [{firebaseAuth: []}], summary: "Cancel an owned pickup request", responses: {"200": {description: "Pickup cancelled"}}}},
    "/pickup-requests/{id}/reschedule": {patch: {security: [{firebaseAuth: []}], summary: "Reschedule an owned pickup request", responses: {"200": {description: "Pickup rescheduled"}}}},
    "/pickup-requests/{id}/rating": {patch: {security: [{firebaseAuth: []}], summary: "Rate a completed pickup", responses: {"200": {description: "Rating saved"}}}},
    "/dispatch/schedules": {
      get: {security: [{firebaseAuth: []}], summary: "List collection schedules in a date range", responses: {"200": {description: "Role-filtered schedules"}}},
      post: {security: [{firebaseAuth: []}], summary: "Create and assign a collection schedule", responses: {"201": {description: "Schedule created"}}},
    },
    "/dispatch/assignable-pickups": {get: {security: [{firebaseAuth: []}], summary: "List pickups ready for assignment", responses: {"200": {description: "Assignable pickups"}}}},
    "/dispatch/staff": {get: {security: [{firebaseAuth: []}], summary: "List collectors and drivers", responses: {"200": {description: "Dispatch staff"}}}},
    "/dispatch/schedules/{id}/dispatch": {patch: {security: [{firebaseAuth: []}], summary: "Dispatch an assigned collection team", responses: {"200": {description: "Schedule dispatched"}}}},
    "/dispatch/schedules/{id}/start": {patch: {security: [{firebaseAuth: []}], summary: "Start an assigned collection", responses: {"200": {description: "Collection started"}}}},
    "/dispatch/schedules/{id}/complete": {patch: {security: [{firebaseAuth: []}], summary: "Complete an assigned collection", responses: {"200": {description: "Collection completed"}}}},
    "/dispatch/schedules/{id}/reschedule": {patch: {security: [{firebaseAuth: []}], summary: "Reschedule a missed collection", responses: {"200": {description: "Collection rescheduled"}}}},
    "/routes": {get: {security: [{firebaseAuth: []}], summary: "List routes visible to the authenticated user", responses: {"200": {description: "Role-filtered routes"}}}},
    "/routes/schedulable": {get: {security: [{firebaseAuth: []}], summary: "List schedules available for route generation", responses: {"200": {description: "Schedulable collections"}}}},
    "/routes/optimize": {post: {security: [{firebaseAuth: []}], summary: "Generate an ordered route from pickup GPS coordinates", responses: {"201": {description: "Route generated"}}}},
    "/routes/{id}": {get: {security: [{firebaseAuth: []}], summary: "Return an accessible route", responses: {"200": {description: "Route details"}}}},
    "/routes/{id}/start": {patch: {security: [{firebaseAuth: []}], summary: "Start live route navigation", responses: {"200": {description: "Route activated"}}}},
    "/routes/{id}/positions": {post: {security: [{firebaseAuth: []}], summary: "Record an assigned driver's GPS position", responses: {"200": {description: "Position processed"}}}},
    "/routes/{id}/complete": {patch: {security: [{firebaseAuth: []}], summary: "Complete an assigned route", responses: {"200": {description: "Route completed"}}}},
    "/collection-centres/{id}": {get: {security: [{firebaseAuth: []}], summary: "Return an operational collection-centre record", responses: {"200": {description: "Collection centre"}}}},
    "/collection-centres/{id}/storageSections": {get: {security: [{firebaseAuth: []}], summary: "List storage sections", responses: {"200": {description: "Storage sections"}}}},
    "/collection-centres/{id}/receivingRecords": {get: {security: [{firebaseAuth: []}], summary: "List receiving records", responses: {"200": {description: "Receiving records"}}}},
    "/collection-centres/{id}/stockMovements": {get: {security: [{firebaseAuth: []}], summary: "List stock movements", responses: {"200": {description: "Stock movements"}}}},
    "/collection-centres/{id}/staffAssignments": {get: {security: [{firebaseAuth: []}], summary: "List centre staff assignments", responses: {"200": {description: "Staff assignments"}}}},
    "/collection-centres/{id}/safetyInspections": {get: {security: [{firebaseAuth: []}], summary: "List safety inspections", responses: {"200": {description: "Safety inspections"}}}},
    "/collection-centres/{id}/sections": {post: {security: [{firebaseAuth: []}], summary: "Create a storage section", responses: {"201": {description: "Section created"}}}},
    "/collection-centres/{id}/staff": {post: {security: [{firebaseAuth: []}], summary: "Assign centre staff", responses: {"201": {description: "Staff assigned"}}}},
    "/collection-centres/{id}/check-ins": {post: {security: [{firebaseAuth: []}], summary: "Receive and check in e-waste", responses: {"201": {description: "Receiving record created"}}}},
    "/collection-centres/{id}/receiving/{recordId}/verify": {patch: {security: [{firebaseAuth: []}], summary: "Verify a receiving weight", responses: {"200": {description: "Weight verified"}}}},
    "/collection-centres/{id}/check-outs": {post: {security: [{firebaseAuth: []}], summary: "Check stock out of a centre", responses: {"201": {description: "Stock checked out"}}}},
    "/collection-centres/{id}/inspections": {post: {security: [{firebaseAuth: []}], summary: "Record a safety inspection", responses: {"201": {description: "Inspection recorded"}}}},
    "/inventory/items": {
      get: {security: [{firebaseAuth: []}], summary: "List e-waste inventory items", responses: {"200": {description: "Inventory items"}}},
      post: {security: [{firebaseAuth: []}], summary: "Register a tracked e-waste item", responses: {"201": {description: "Item registered"}}},
    },
    "/inventory/items/by-code/{code}": {get: {security: [{firebaseAuth: []}], summary: "Find an item by its EcoTrace code", responses: {"200": {description: "Inventory item"}}}},
    "/inventory/items/{id}/history": {get: {security: [{firebaseAuth: []}], summary: "List item processing history", responses: {"200": {description: "History events"}}}},
    "/inventory/items/{id}/state": {patch: {security: [{firebaseAuth: []}], summary: "Move an item to a processing state and location", responses: {"200": {description: "Item updated"}}}},
    "/inventory/batches": {
      get: {security: [{firebaseAuth: []}], summary: "List inventory batches", responses: {"200": {description: "Inventory batches"}}},
      post: {security: [{firebaseAuth: []}], summary: "Create an inventory batch", responses: {"201": {description: "Batch created"}}},
    },
    "/inventory/items/{id}/batch": {patch: {security: [{firebaseAuth: []}], summary: "Assign an item to an inventory batch", responses: {"200": {description: "Batch assigned"}}}},
    "/inventory/items/{id}/assessments": {
      get: {security: [{firebaseAuth: []}], summary: "List item classification assessments", responses: {"200": {description: "Assessments"}}},
      post: {security: [{firebaseAuth: []}], summary: "Submit an item classification assessment", responses: {"201": {description: "Assessment submitted"}}},
    },
    "/inventory/items/{id}/assessments/{assessmentId}/review": {patch: {security: [{firebaseAuth: []}], summary: "Approve or reject a classification assessment", responses: {"200": {description: "Assessment reviewed"}}}},
    "/inventory/items/{id}/traceability": {
      get: {security: [{firebaseAuth: []}], summary: "List chain-of-custody events", responses: {"200": {description: "Traceability events"}}},
      post: {security: [{firebaseAuth: []}], summary: "Record a chain-of-custody event", responses: {"201": {description: "Traceability event recorded"}}},
    },
  },
};
