export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "EcoTrace API",
    version: "1.0.0",
    description: "Versioned API for EcoTrace e-waste collection and processing workflows.",
  },
  servers: [{url: "/api/v1", description: "Current deployment"}],
  components: {
    securitySchemes: {
      firebaseAuth: {type: "http", scheme: "bearer", bearerFormat: "Firebase ID token"},
    },
  },
  paths: {
    "/media/upload-signature": {post: {security: [{firebaseAuth: []}], summary: "Create a short-lived signed Cloudinary image upload request", responses: {"200": {description: "Signed upload parameters"}}}},
    "/me": {get: {security: [{firebaseAuth: []}], summary: "Return the authenticated user profile", responses: {"200": {description: "Current user"}}}},
    "/admin/demo-data": {post: {security: [{firebaseAuth: []}], summary: "Create deterministic dashboard demo records", responses: {"200": {description: "Demo records created or refreshed"}}}},
    "/collection-centres": {
      get: {summary: "List the public collection-centre directory", responses: {"200": {description: "Active centres"}}},
      post: {security: [{firebaseAuth: []}], summary: "Register a collection centre", responses: {"201": {description: "Centre created"}}},
    },
    "/vehicles": {
      get: {security: [{firebaseAuth: []}], summary: "List vehicles", responses: {"200": {description: "Vehicles"}}},
      post: {security: [{firebaseAuth: []}], summary: "Register a vehicle", responses: {"201": {description: "Vehicle created"}}},
    },
    "/pickup-requests": {
      get: {security: [{firebaseAuth: []}], summary: "List accessible pickup requests", responses: {"200": {description: "Pickup requests"}}},
      post: {security: [{firebaseAuth: []}], summary: "Submit a pickup request", responses: {"201": {description: "Pickup created"}}},
    },
    "/pickup-requests/{id}/cancel": {patch: {security: [{firebaseAuth: []}], summary: "Cancel an owned pickup request", responses: {"200": {description: "Pickup cancelled"}}}},
    "/pickup-requests/{id}/reschedule": {patch: {security: [{firebaseAuth: []}], summary: "Reschedule an owned pickup request", responses: {"200": {description: "Pickup rescheduled"}}}},
    "/pickup-requests/{id}/rating": {patch: {security: [{firebaseAuth: []}], summary: "Rate a completed pickup", responses: {"200": {description: "Rating saved"}}}},
    "/dispatch/schedules": {
      get: {security: [{firebaseAuth: []}], summary: "List collection schedules in a date range", responses: {"200": {description: "Role-filtered schedules"}}},
      post: {security: [{firebaseAuth: []}], summary: "Create and assign a collection schedule", responses: {"201": {description: "Schedule created"}}},
    },
    "/dispatch/assignable-pickups": {get: {security: [{firebaseAuth: []}], summary: "List pickups ready for assignment", responses: {"200": {description: "Assignable pickups"}}}},
    "/dispatch/staff": {get: {security: [{firebaseAuth: []}], summary: "List collectors and drivers", responses: {"200": {description: "Dispatch staff"}}}},
    "/dispatch/schedules/{id}/dispatch": {patch: {security: [{firebaseAuth: []}], summary: "Dispatch an assigned collection team", responses: {"200": {description: "Schedule dispatched"}}}},
    "/dispatch/schedules/{id}/start": {patch: {security: [{firebaseAuth: []}], summary: "Start an assigned collection", responses: {"200": {description: "Collection started"}}}},
    "/dispatch/schedules/{id}/complete": {patch: {security: [{firebaseAuth: []}], summary: "Complete an assigned collection", responses: {"200": {description: "Collection completed"}}}},
    "/dispatch/schedules/{id}/reschedule": {patch: {security: [{firebaseAuth: []}], summary: "Reschedule a missed collection", responses: {"200": {description: "Collection rescheduled"}}}},
    "/routes": {get: {security: [{firebaseAuth: []}], summary: "List routes visible to the authenticated user", responses: {"200": {description: "Role-filtered routes"}}}},
    "/routes/schedulable": {get: {security: [{firebaseAuth: []}], summary: "List schedules available for route generation", responses: {"200": {description: "Schedulable collections"}}}},
    "/routes/optimize": {post: {security: [{firebaseAuth: []}], summary: "Generate an ordered route from pickup GPS coordinates", responses: {"201": {description: "Route generated"}}}},
    "/routes/{id}": {get: {security: [{firebaseAuth: []}], summary: "Return an accessible route", responses: {"200": {description: "Route details"}}}},
    "/routes/{id}/start": {patch: {security: [{firebaseAuth: []}], summary: "Start live route navigation", responses: {"200": {description: "Route activated"}}}},
    "/routes/{id}/positions": {post: {security: [{firebaseAuth: []}], summary: "Record an assigned driver's GPS position", responses: {"200": {description: "Position processed"}}}},
    "/routes/{id}/complete": {patch: {security: [{firebaseAuth: []}], summary: "Complete an assigned route", responses: {"200": {description: "Route completed"}}}},
    "/collection-centres/{id}": {get: {security: [{firebaseAuth: []}], summary: "Return an operational collection-centre record", responses: {"200": {description: "Collection centre"}}}},
    "/collection-centres/{id}/storageSections": {get: {security: [{firebaseAuth: []}], summary: "List storage sections", responses: {"200": {description: "Storage sections"}}}},
    "/collection-centres/{id}/receivingRecords": {get: {security: [{firebaseAuth: []}], summary: "List receiving records", responses: {"200": {description: "Receiving records"}}}},
    "/collection-centres/{id}/stockMovements": {get: {security: [{firebaseAuth: []}], summary: "List stock movements", responses: {"200": {description: "Stock movements"}}}},
    "/collection-centres/{id}/staffAssignments": {get: {security: [{firebaseAuth: []}], summary: "List centre staff assignments", responses: {"200": {description: "Staff assignments"}}}},
    "/collection-centres/{id}/safetyInspections": {get: {security: [{firebaseAuth: []}], summary: "List safety inspections", responses: {"200": {description: "Safety inspections"}}}},
    "/collection-centres/{id}/sections": {post: {security: [{firebaseAuth: []}], summary: "Create a storage section", responses: {"201": {description: "Section created"}}}},
    "/collection-centres/{id}/staff": {post: {security: [{firebaseAuth: []}], summary: "Assign centre staff", responses: {"201": {description: "Staff assigned"}}}},
    "/collection-centres/{id}/check-ins": {post: {security: [{firebaseAuth: []}], summary: "Receive and check in e-waste", responses: {"201": {description: "Receiving record created"}}}},
    "/collection-centres/{id}/receiving/{recordId}/verify": {patch: {security: [{firebaseAuth: []}], summary: "Verify a receiving weight", responses: {"200": {description: "Weight verified"}}}},
    "/collection-centres/{id}/check-outs": {post: {security: [{firebaseAuth: []}], summary: "Check stock out of a centre", responses: {"201": {description: "Stock checked out"}}}},
    "/collection-centres/{id}/inspections": {post: {security: [{firebaseAuth: []}], summary: "Record a safety inspection", responses: {"201": {description: "Inspection recorded"}}}},
    "/inventory/items": {
      get: {security: [{firebaseAuth: []}], summary: "List e-waste inventory items", responses: {"200": {description: "Inventory items"}}},
      post: {security: [{firebaseAuth: []}], summary: "Register a tracked e-waste item", responses: {"201": {description: "Item registered"}}},
    },
    "/inventory/items/by-code/{code}": {get: {security: [{firebaseAuth: []}], summary: "Find an item by its EcoTrace code", responses: {"200": {description: "Inventory item"}}}},
    "/inventory/items/{id}/history": {get: {security: [{firebaseAuth: []}], summary: "List item processing history", responses: {"200": {description: "History events"}}}},
    "/inventory/items/{id}/state": {patch: {security: [{firebaseAuth: []}], summary: "Move an item to a processing state and location", responses: {"200": {description: "Item updated"}}}},
    "/inventory/batches": {
      get: {security: [{firebaseAuth: []}], summary: "List inventory batches", responses: {"200": {description: "Inventory batches"}}},
      post: {security: [{firebaseAuth: []}], summary: "Create an inventory batch", responses: {"201": {description: "Batch created"}}},
    },
    "/inventory/items/{id}/batch": {patch: {security: [{firebaseAuth: []}], summary: "Assign an item to an inventory batch", responses: {"200": {description: "Batch assigned"}}}},
    "/inventory/items/{id}/assessments": {
      get: {security: [{firebaseAuth: []}], summary: "List item classification assessments", responses: {"200": {description: "Assessments"}}},
      post: {security: [{firebaseAuth: []}], summary: "Submit an item classification assessment", responses: {"201": {description: "Assessment submitted"}}},
    },
    "/inventory/items/{id}/assessments/{assessmentId}/review": {patch: {security: [{firebaseAuth: []}], summary: "Approve or reject a classification assessment", responses: {"200": {description: "Assessment reviewed"}}}},
    "/inventory/items/{id}/traceability": {
      get: {security: [{firebaseAuth: []}], summary: "List chain-of-custody events", responses: {"200": {description: "Traceability events"}}},
      post: {security: [{firebaseAuth: []}], summary: "Record a chain-of-custody event", responses: {"201": {description: "Traceability event recorded"}}},
    },
    "/repairs": {get: {security: [{firebaseAuth: []}], summary: "List accessible repair jobs", responses: {"200": {description: "Repair jobs"}}}, post: {security: [{firebaseAuth: []}], summary: "Create a repair assessment", responses: {"201": {description: "Repair job created"}}}},
    "/repairs/{id}": {get: {security: [{firebaseAuth: []}], summary: "Return a repair job", responses: {"200": {description: "Repair job"}}}},
    "/repairs/{id}/assignment": {patch: {security: [{firebaseAuth: []}], summary: "Assign a repair technician", responses: {"200": {description: "Technician assigned"}}}},
    "/repairs/{id}/diagnosis": {patch: {security: [{firebaseAuth: []}], summary: "Record diagnosis, faults, and cost estimate", responses: {"200": {description: "Diagnosis recorded"}}}},
    "/repairs/{id}/review": {patch: {security: [{firebaseAuth: []}], summary: "Approve or reject a repair", responses: {"200": {description: "Repair reviewed"}}}},
    "/repairs/{id}/start": {patch: {security: [{firebaseAuth: []}], summary: "Start an approved repair", responses: {"200": {description: "Repair started"}}}},
    "/repairs/{id}/parts": {get: {security: [{firebaseAuth: []}], summary: "List spare parts used", responses: {"200": {description: "Spare parts"}}}, post: {security: [{firebaseAuth: []}], summary: "Record a spare part", responses: {"201": {description: "Spare part recorded"}}}},
    "/repairs/{id}/progress": {get: {security: [{firebaseAuth: []}], summary: "List repair progress events", responses: {"200": {description: "Progress events"}}}, patch: {security: [{firebaseAuth: []}], summary: "Update repair progress", responses: {"200": {description: "Progress updated"}}}},
    "/repairs/{id}/quality-testing": {patch: {security: [{firebaseAuth: []}], summary: "Submit repair for quality testing", responses: {"200": {description: "Quality testing started"}}}},
    "/repairs/{id}/quality-control": {patch: {security: [{firebaseAuth: []}], summary: "Complete quality control and refurbishment grading", responses: {"200": {description: "Quality control recorded"}}}},
    "/repairs/{id}/unrepairable": {patch: {security: [{firebaseAuth: []}], summary: "Mark an item unrepairable and send it to recycling", responses: {"200": {description: "Repair closed"}}}},
    "/repairs/{id}/warranty": {patch: {security: [{firebaseAuth: []}], summary: "Update refurbished-device warranty", responses: {"200": {description: "Warranty updated"}}}},
    "/repairs/{id}/disposition": {patch: {security: [{firebaseAuth: []}], summary: "Approve a repaired device for donation or resale", responses: {"200": {description: "Disposition approved"}}}},
    "/recycling/batches": {get: {security: [{firebaseAuth: []}], summary: "List recycling batches", responses: {"200": {description: "Recycling batches"}}}, post: {security: [{firebaseAuth: []}], summary: "Create a recycling batch", responses: {"201": {description: "Batch created"}}}},
    "/recycling/batches/{id}": {get: {security: [{firebaseAuth: []}], summary: "Return a recycling batch", responses: {"200": {description: "Recycling batch"}}}},
    "/recycling/batches/{id}/facility": {patch: {security: [{firebaseAuth: []}], summary: "Assign a recycling facility", responses: {"200": {description: "Facility assigned"}}}},
    "/recycling/batches/{id}/stage": {patch: {security: [{firebaseAuth: []}], summary: "Advance the recycling stage", responses: {"200": {description: "Stage updated"}}}},
    "/recycling/batches/{id}/process-records": {get: {security: [{firebaseAuth: []}], summary: "List dismantling and separation records", responses: {"200": {description: "Process records"}}}, post: {security: [{firebaseAuth: []}], summary: "Record recycling work", responses: {"201": {description: "Process record created"}}}},
    "/recycling/batches/{id}/outputs": {post: {security: [{firebaseAuth: []}], summary: "Record recovered or hazardous material", responses: {"201": {description: "Output recorded"}}}},
    "/recycling/batches/{id}/losses": {post: {security: [{firebaseAuth: []}], summary: "Record a processing loss", responses: {"201": {description: "Loss recorded"}}}},
    "/recycling/batches/{id}/disposals": {get: {security: [{firebaseAuth: []}], summary: "List final disposal records", responses: {"200": {description: "Disposal records"}}}, post: {security: [{firebaseAuth: []}], summary: "Record final disposal", responses: {"201": {description: "Disposal recorded"}}}},
    "/recycling/batches/{id}/verify": {patch: {security: [{firebaseAuth: []}], summary: "Verify recycling completion", responses: {"200": {description: "Batch completed"}}}},
    "/recycling/batches/{id}/certificate": {get: {security: [{firebaseAuth: []}], summary: "Generate recycling certificate data", responses: {"200": {description: "Certificate data"}}}},
    "/recycling/reports/summary": {get: {security: [{firebaseAuth: []}], summary: "Return recycling performance totals", responses: {"200": {description: "Recycling performance"}}}},
    "/recovery/categories": {get: {security: [{firebaseAuth: []}], summary: "List recoverable material categories", responses: {"200": {description: "Material categories"}}}},
    "/recovery/categories/{material}": {patch: {security: [{firebaseAuth: []}], summary: "Create or update a material category", responses: {"200": {description: "Category saved"}}}},
    "/recovery/buyers": {get: {security: [{firebaseAuth: []}], summary: "List material buyers", responses: {"200": {description: "Material buyers"}}}, post: {security: [{firebaseAuth: []}], summary: "Register a material buyer", responses: {"201": {description: "Buyer created"}}}},
    "/recovery/lots": {get: {security: [{firebaseAuth: []}], summary: "List recovered material lots", responses: {"200": {description: "Recovered material lots"}}}, post: {security: [{firebaseAuth: []}], summary: "Record recovered material and update batch mass balance", responses: {"201": {description: "Material lot created"}}}},
    "/recovery/lots/{id}": {get: {security: [{firebaseAuth: []}], summary: "Return a recovered material lot", responses: {"200": {description: "Material lot"}}}},
    "/recovery/lots/{id}/buyer": {patch: {security: [{firebaseAuth: []}], summary: "Assign a material buyer", responses: {"200": {description: "Buyer assigned"}}}},
    "/recovery/lots/{id}/sales-ready": {patch: {security: [{firebaseAuth: []}], summary: "Mark material as sales-ready", responses: {"200": {description: "Lot is sales-ready"}}}},
    "/recovery/lots/{id}/transfers": {get: {security: [{firebaseAuth: []}], summary: "List material transfer records", responses: {"200": {description: "Transfer records"}}}, post: {security: [{firebaseAuth: []}], summary: "Transfer a material lot", responses: {"201": {description: "Transfer recorded"}}}},
    "/recovery/lots/{id}/sale": {post: {security: [{firebaseAuth: []}], summary: "Record recovered-material sale revenue", responses: {"200": {description: "Sale recorded"}}}},
    "/recovery/reports/summary": {get: {security: [{firebaseAuth: []}], summary: "Return recovery inventory, efficiency, value, and revenue totals", responses: {"200": {description: "Resource recovery summary"}}}},
  },
};
