import {Router} from "express";
import {FieldValue, Timestamp} from "firebase-admin/firestore";
import {z} from "zod";
import {authenticate, requireRoles} from "./auth.js";
import {ApiError} from "./errors.js";
import {db} from "./firebase.js";
import {documentJson} from "./firestore-json.js";

const router = Router(); const managers = ["environmentalOfficer", "administrator", "superAdministrator"] as const;
const reportTypes = ["collection", "pickup", "inventory", "recycling", "repair", "resourceRecovery", "environmentalImpact", "user", "partner", "financial", "compliance", "incident", "custom"] as const;
const sourceMap: Record<string, string> = {collection: "collectionSchedules", pickup: "pickupRequests", inventory: "inventoryItems", recycling: "recyclingBatches", repair: "repairJobs", resourceRecovery: "recoveredMaterialLots", environmentalImpact: "environmentalImpactSnapshots", user: "users", partner: "partners", financial: "paymentTransactions", compliance: "complianceRecords", incident: "incidents"};
function id(value: string | string[]) { return Array.isArray(value) ? value[0] : value; }
async function definition(reportId: string) { const ref = db.collection("reportDefinitions").doc(reportId); const snapshot = await ref.get(); if (!snapshot.exists) throw new ApiError(404, "Report definition not found.", "not_found"); return {ref, snapshot}; }

router.get("/reports/definitions", authenticate, requireRoles(...managers), async (_request, response) => { const snapshot = await db.collection("reportDefinitions").limit(300).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.post("/reports/definitions", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({name: z.string().trim().min(2).max(300), type: z.enum(reportTypes), sourceCollection: z.string().trim().max(200).default(""), fields: z.array(z.string().trim().min(1)).min(1), filters: z.array(z.object({field: z.string().trim().min(1), operator: z.enum(["==", ">=", "<=", "array-contains"]), value: z.union([z.string(), z.number(), z.boolean()])})).default([]), groupBy: z.string().trim().max(100).default(""), metrics: z.array(z.enum(["count", "sum", "average", "minimum", "maximum"])).default(["count"]), active: z.boolean().default(true)}).parse(request.body); const sourceCollection = input.type === "custom" ? input.sourceCollection : sourceMap[input.type]; if (!sourceCollection) throw new ApiError(400, "A source collection is required for custom reports.", "invalid_argument"); const ref = await db.collection("reportDefinitions").add({...input, sourceCollection, createdBy: request.user!.uid, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.status(201).json({data: {id: ref.id}}); });
router.get("/reports/definitions/:id", authenticate, requireRoles(...managers), async (request, response) => { const report = await definition(id(request.params.id)); response.json({data: documentJson(report.snapshot.id, report.snapshot.data()!)}); });
router.patch("/reports/definitions/:id", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({name: z.string().trim().min(2).max(300).optional(), fields: z.array(z.string().trim().min(1)).min(1).optional(), active: z.boolean().optional()}).refine((value) => Object.keys(value).length > 0).parse(request.body); const report = await definition(id(request.params.id)); await report.ref.update({...input, updatedBy: request.user!.uid, updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: report.ref.id}}); });
router.delete("/reports/definitions/:id", authenticate, requireRoles(...managers), async (request, response) => { const report = await definition(id(request.params.id)); await report.ref.update({active: false, archivedBy: request.user!.uid, archivedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: report.ref.id, archived: true}}); });

router.post("/reports/generate", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({definitionId: z.string().trim().min(1), from: z.coerce.date(), to: z.coerce.date(), format: z.enum(["json", "pdf", "csv", "xlsx"]).default("json")}).parse(request.body); if (input.to <= input.from) throw new ApiError(400, "Report end must be after start.", "invalid_argument"); const report = await definition(input.definitionId); let query: FirebaseFirestore.Query = db.collection(String(report.snapshot.get("sourceCollection"))).where("createdAt", ">=", Timestamp.fromDate(input.from)).where("createdAt", "<=", Timestamp.fromDate(input.to)); for (const filter of report.snapshot.get("filters") ?? []) query = query.where(String(filter.field), filter.operator, filter.value); const snapshot = await query.limit(5000).get(); const fields: string[] = report.snapshot.get("fields") ?? []; const rows = snapshot.docs.map((doc) => { const row: Record<string, unknown> = {id: doc.id}; for (const field of fields) row[field] = doc.get(field) ?? null; return row; }); const output = db.collection("generatedReports").doc(); await output.set({definitionId: report.ref.id, name: report.snapshot.get("name"), type: report.snapshot.get("type"), from: Timestamp.fromDate(input.from), to: Timestamp.fromDate(input.to), format: input.format, recordCount: rows.length, status: input.format === "json" ? "completed" : "queued", requestedBy: request.user!.uid, createdAt: FieldValue.serverTimestamp(), data: input.format === "json" ? rows : []}); response.status(input.format === "json" ? 201 : 202).json({data: {id: output.id, status: input.format === "json" ? "completed" : "queued", recordCount: rows.length, rows: input.format === "json" ? rows : undefined}}); });

router.post("/reports/schedules", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({definitionId: z.string().trim().min(1), frequency: z.enum(["daily", "weekly", "monthly", "quarterly"]), format: z.enum(["pdf", "csv", "xlsx"]), recipientEmails: z.array(z.string().email()).min(1), nextRunAt: z.coerce.date(), active: z.boolean().default(true)}).parse(request.body); await definition(input.definitionId); const ref = await db.collection("reportSchedules").add({...input, nextRunAt: Timestamp.fromDate(input.nextRunAt), createdBy: request.user!.uid, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.status(201).json({data: {id: ref.id}}); });
router.get("/reports/schedules", authenticate, requireRoles(...managers), async (_request, response) => { const snapshot = await db.collection("reportSchedules").limit(300).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.patch("/reports/schedules/:id", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({active: z.boolean().optional(), nextRunAt: z.coerce.date().optional(), recipientEmails: z.array(z.string().email()).min(1).optional()}).refine((value) => Object.keys(value).length > 0, "At least one field is required.").parse(request.body); const ref = db.collection("reportSchedules").doc(id(request.params.id)); const snapshot = await ref.get(); if (!snapshot.exists) throw new ApiError(404, "Report schedule not found.", "not_found"); await ref.update({...input, ...(input.nextRunAt ? {nextRunAt: Timestamp.fromDate(input.nextRunAt)} : {}), updatedBy: request.user!.uid, updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: ref.id}}); });
router.delete("/reports/schedules/:id", authenticate, requireRoles(...managers), async (request, response) => { const ref = db.collection("reportSchedules").doc(id(request.params.id)); if (!(await ref.get()).exists) throw new ApiError(404, "Report schedule not found.", "not_found"); await ref.update({active: false, archivedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: ref.id, archived: true}}); });
router.get("/reports/generated", authenticate, requireRoles(...managers), async (request, response) => { let query: FirebaseFirestore.Query = db.collection("generatedReports"); if (typeof request.query.type === "string") query = query.where("type", "==", request.query.type); const snapshot = await query.limit(500).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.get("/reports/generated/:id", authenticate, requireRoles(...managers), async (request, response) => { const snapshot = await db.collection("generatedReports").doc(id(request.params.id)).get(); if (!snapshot.exists) throw new ApiError(404, "Generated report not found.", "not_found"); response.json({data: documentJson(snapshot.id, snapshot.data()!)}); });
router.get("/reports/catalog", authenticate, requireRoles(...managers), async (_request, response) => { response.json({data: reportTypes.map((type) => ({type, defaultSource: sourceMap[type] ?? "custom", supportedFormats: ["json", "pdf", "csv", "xlsx"]}))}); });

export default router;
