import {Router} from "express";
import {FieldValue, Timestamp} from "firebase-admin/firestore";
import type * as FirebaseFirestore from "firebase-admin/firestore";
import {z} from "zod";
import {authenticate, requireRoles} from "./auth.js";
import {ApiError} from "./errors.js";
import {db} from "./firebase.js";
import {documentJson} from "./firestore-json.js";
import {publishNotificationEvent} from "./push-events.js";

const router = Router();
const users = ["household", "business", "institution", "collector", "driver", "collectionCentreOperator", "repairTechnician", "recycler", "environmentalOfficer", "administrator", "superAdministrator"] as const;
const managers = ["administrator", "superAdministrator"] as const;

function id(value: string | string[]) { return Array.isArray(value) ? value[0] : value; }
function number(value: unknown) { return Number(value ?? 0); }
function level(points: number) { if (points >= 10000) return "platinum"; if (points >= 5000) return "gold"; if (points >= 1500) return "silver"; return "greenStarter"; }
async function wallet(uid: string) { const ref = db.collection("rewardWallets").doc(uid); const snapshot = await ref.get(); return {ref, snapshot}; }

router.get("/rewards/wallet", authenticate, requireRoles(...users), async (request, response) => {
  const current = await wallet(request.user!.uid); const data = current.snapshot.exists ? current.snapshot.data()! : {userId: request.user!.uid, balance: 0, lifetimeEarned: 0, lifetimeRedeemed: 0, level: "greenStarter"}; response.json({data: documentJson(request.user!.uid, data)});
});

router.get("/rewards/history", authenticate, requireRoles(...users), async (request, response) => {
  const snapshot = await db.collection("rewardWallets").doc(request.user!.uid).collection("transactions").orderBy("createdAt", "desc").limit(300).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))});
});

router.get("/rewards/rules", authenticate, requireRoles(...users), async (_request, response) => { const snapshot = await db.collection("rewardRules").where("active", "==", true).limit(100).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });

router.put("/rewards/rules/:id", authenticate, requireRoles(...managers), async (request, response) => {
  const input = z.object({name: z.string().trim().min(2).max(200), event: z.enum(["pickupCompleted", "referralCompleted", "challengeCompleted", "materialRecovered", "deviceDonated", "partnerBonus"]), points: z.number().int().positive(), multiplierPerKg: z.number().nonnegative().default(0), expiresAfterDays: z.number().int().min(1).max(3650).default(365), dailyLimit: z.number().int().positive().default(10), active: z.boolean()}).parse(request.body); const ruleId = id(request.params.id); await db.collection("rewardRules").doc(ruleId).set({...input, updatedBy: request.user!.uid, updatedAt: FieldValue.serverTimestamp()}, {merge: true}); response.json({data: {id: ruleId}});
});

router.post("/rewards/award", authenticate, requireRoles(...managers), async (request, response) => {
  const input = z.object({userId: z.string().trim().min(1), ruleId: z.string().trim().min(1), referenceId: z.string().trim().min(1), weightKg: z.number().nonnegative().default(0), notes: z.string().trim().max(1000).default("")}).parse(request.body); const rule = await db.collection("rewardRules").doc(input.ruleId).get(); if (!rule.exists || rule.get("active") !== true) throw new ApiError(404, "Active reward rule not found.", "not_found"); const duplicate = await db.collection("rewardWallets").doc(input.userId).collection("transactions").where("referenceId", "==", input.referenceId).where("ruleId", "==", input.ruleId).limit(1).get(); if (!duplicate.empty) throw new ApiError(409, "This reward was already issued.", "duplicate_reward"); const points = Math.round(number(rule.get("points")) + number(rule.get("multiplierPerKg")) * input.weightKg); const expiresAt = Timestamp.fromMillis(Date.now() + number(rule.get("expiresAfterDays")) * 86400000); const current = await wallet(input.userId); const newLifetime = number(current.snapshot.get("lifetimeEarned")) + points; const transaction = current.ref.collection("transactions").doc(); const batch = db.batch(); batch.set(current.ref, {userId: input.userId, balance: FieldValue.increment(points), lifetimeEarned: FieldValue.increment(points), lifetimeRedeemed: number(current.snapshot.get("lifetimeRedeemed")), level: level(newLifetime), updatedAt: FieldValue.serverTimestamp(), createdAt: current.snapshot.exists ? current.snapshot.get("createdAt") ?? FieldValue.serverTimestamp() : FieldValue.serverTimestamp()}, {merge: true}); batch.set(transaction, {...input, type: "credit", points, expiresAt, status: "active", awardedBy: request.user!.uid, createdAt: FieldValue.serverTimestamp()}); await batch.commit(); void publishNotificationEvent({event: "reward_points_awarded", recipientId: input.userId, data: {points, transactionId: transaction.id}}); response.status(201).json({data: {id: transaction.id, points, level: level(newLifetime)}});
});

router.post("/rewards/adjustments", authenticate, requireRoles(...managers), async (request, response) => {
  const input = z.object({userId: z.string().trim().min(1), points: z.number().int().refine((value) => value !== 0, "Points cannot be zero."), referenceId: z.string().trim().min(1), description: z.string().trim().min(2).max(1000), expiresAfterDays: z.number().int().min(1).max(3650).default(365)}).parse(request.body);
  const current = await wallet(input.userId); const transaction = current.ref.collection("transactions").doc(`adjustment-${input.referenceId}`); if ((await transaction.get()).exists) throw new ApiError(409, "This adjustment was already processed.", "duplicate_reward");
  const balance = number(current.snapshot.get("balance")); if (input.points < 0 && balance < Math.abs(input.points)) throw new ApiError(409, "The wallet balance is insufficient.", "insufficient_points");
  const lifetime = number(current.snapshot.get("lifetimeEarned")) + Math.max(0, input.points); const batch = db.batch(); batch.set(current.ref, {userId: input.userId, balance: FieldValue.increment(input.points), lifetimeEarned: FieldValue.increment(Math.max(0, input.points)), level: level(lifetime), updatedAt: FieldValue.serverTimestamp()}, {merge: true}); batch.set(transaction, {...input, type: input.points > 0 ? "credit" : "debit", status: "active", awardedBy: request.user!.uid, expiresAt: input.points > 0 ? Timestamp.fromMillis(Date.now() + input.expiresAfterDays * 86400000) : null, createdAt: FieldValue.serverTimestamp()}); await batch.commit(); void publishNotificationEvent({event: "reward_points_awarded", recipientId: input.userId, data: {points: input.points, transactionId: transaction.id}}); response.status(201).json({data: {id: transaction.id, points: input.points}});
});

router.post("/rewards/expiry", authenticate, requireRoles(...managers), async (request, response) => {
  const input = z.object({userId: z.string().trim().min(1), points: z.number().int().positive(), referenceId: z.string().trim().min(1)}).parse(request.body); const current = await wallet(input.userId); const amount = Math.min(input.points, number(current.snapshot.get("balance"))); const transaction = current.ref.collection("transactions").doc(`expiry-${input.referenceId}`); if ((await transaction.get()).exists) throw new ApiError(409, "This expiry was already processed.", "duplicate_reward"); const batch = db.batch(); batch.set(current.ref, {balance: FieldValue.increment(-amount), updatedAt: FieldValue.serverTimestamp()}, {merge: true}); batch.set(transaction, {type: "expiry", points: -amount, referenceId: input.referenceId, description: "Expired green points", status: "completed", createdAt: FieldValue.serverTimestamp()}); await batch.commit(); void publishNotificationEvent({event: "reward_points_expired", recipientId: input.userId, data: {points: amount}}); response.status(201).json({data: {id: transaction.id, pointsExpired: amount}});
});

router.post("/rewards/referrals", authenticate, requireRoles(...users), async (request, response) => {
  const input = z.object({referredEmail: z.string().trim().email()}).parse(request.body); if (input.referredEmail.toLowerCase() === (request.user!.email ?? "").toLowerCase()) throw new ApiError(400, "You cannot refer yourself.", "invalid_argument"); const existing = await db.collection("rewardReferrals").where("referredEmail", "==", input.referredEmail.toLowerCase()).limit(1).get(); if (!existing.empty) throw new ApiError(409, "This email has already been referred.", "duplicate_referral"); const ref = db.collection("rewardReferrals").doc(); await ref.set({...input, referredEmail: input.referredEmail.toLowerCase(), referralCode: `REF-${ref.id.substring(0, 8).toUpperCase()}`, referrerId: request.user!.uid, status: "invited", createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.status(201).json({data: {id: ref.id, referralCode: `REF-${ref.id.substring(0, 8).toUpperCase()}`}});
});
router.get("/rewards/referrals", authenticate, requireRoles(...users), async (request, response) => { let query: FirebaseFirestore.Query = db.collection("rewardReferrals"); if (!managers.includes(request.user!.role as typeof managers[number])) query = query.where("referrerId", "==", request.user!.uid); const snapshot = await query.limit(300).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });

router.patch("/rewards/referrals/:id/complete", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({referredUserId: z.string().trim().min(1)}).parse(request.body); const ref = db.collection("rewardReferrals").doc(id(request.params.id)); const snapshot = await ref.get(); if (!snapshot.exists) throw new ApiError(404, "Referral not found.", "not_found"); if (snapshot.get("status") !== "invited") throw new ApiError(409, "Referral is already completed.", "invalid_state"); await ref.update({status: "completed", referredUserId: input.referredUserId, completedBy: request.user!.uid, completedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: ref.id, status: "completed", referrerId: snapshot.get("referrerId")}}); });

router.get("/rewards/challenges", authenticate, requireRoles(...users), async (_request, response) => { const snapshot = await db.collection("rewardChallenges").where("active", "==", true).limit(100).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });

router.post("/rewards/challenges", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({title: z.string().trim().min(2).max(300), description: z.string().trim().min(2).max(2000), metric: z.enum(["pickups", "weightKg", "referrals", "donations"]), target: z.number().positive(), rewardPoints: z.number().int().positive(), startsAt: z.coerce.date(), endsAt: z.coerce.date(), participantRoles: z.array(z.string().trim().min(1)).min(1)}).parse(request.body); if (input.endsAt <= input.startsAt) throw new ApiError(400, "Challenge end must be after its start.", "invalid_argument"); const ref = await db.collection("rewardChallenges").add({...input, startsAt: Timestamp.fromDate(input.startsAt), endsAt: Timestamp.fromDate(input.endsAt), active: true, createdBy: request.user!.uid, createdAt: FieldValue.serverTimestamp()}); response.status(201).json({data: {id: ref.id}}); });

router.post("/rewards/challenges/:id/join", authenticate, requireRoles(...users), async (request, response) => { const challenge = await db.collection("rewardChallenges").doc(id(request.params.id)).get(); if (!challenge.exists || challenge.get("active") !== true) throw new ApiError(404, "Active challenge not found.", "not_found"); const ref = challenge.ref.collection("participants").doc(request.user!.uid); await ref.set({userId: request.user!.uid, progress: 0, status: "joined", joinedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}, {merge: true}); response.status(201).json({data: {id: request.user!.uid, status: "joined"}}); });

router.patch("/rewards/challenges/:id/progress", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({userId: z.string().trim().min(1), progress: z.number().nonnegative(), referenceId: z.string().trim().min(1)}).parse(request.body); const challenge = await db.collection("rewardChallenges").doc(id(request.params.id)).get(); if (!challenge.exists || challenge.get("active") !== true) throw new ApiError(404, "Active challenge not found.", "not_found"); const participant = challenge.ref.collection("participants").doc(input.userId); const current = await participant.get(); if (!current.exists) throw new ApiError(404, "Challenge participant not found.", "not_found"); const completed = input.progress >= number(challenge.get("target")); await participant.update({progress: input.progress, status: completed ? "completed" : "inProgress", completionReferenceId: completed ? input.referenceId : "", completedAt: completed ? FieldValue.serverTimestamp() : null, updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: input.userId, status: completed ? "completed" : "inProgress", rewardPoints: completed ? challenge.get("rewardPoints") : 0}}); });

router.get("/rewards/catalog", authenticate, requireRoles(...users), async (_request, response) => { const snapshot = await db.collection("rewardCatalog").where("active", "==", true).limit(200).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });

router.put("/rewards/catalog/:id", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({name: z.string().trim().min(2).max(300), description: z.string().trim().max(1000).default(""), pointsCost: z.number().int().positive(), stock: z.number().int().nonnegative(), type: z.enum(["coupon", "cashback", "product", "partnerReward"]), partnerId: z.string().trim().max(200).default(""), couponPrefix: z.string().trim().min(2).max(20), active: z.boolean()}).parse(request.body); const rewardId = id(request.params.id); await db.collection("rewardCatalog").doc(rewardId).set({...input, updatedBy: request.user!.uid, updatedAt: FieldValue.serverTimestamp()}, {merge: true}); response.json({data: {id: rewardId}}); });

router.get("/rewards/redemptions", authenticate, requireRoles(...users), async (request, response) => { let query: FirebaseFirestore.Query = db.collection("rewardRedemptions"); if (!managers.includes(request.user!.role as typeof managers[number])) query = query.where("userId", "==", request.user!.uid); const snapshot = await query.limit(300).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.post("/rewards/redemptions", authenticate, requireRoles(...users), async (request, response) => { const input = z.object({rewardId: z.string().trim().min(1), quantity: z.number().int().positive().max(100)}).parse(request.body); const rewardRef = db.collection("rewardCatalog").doc(input.rewardId); const walletRef = db.collection("rewardWallets").doc(request.user!.uid); const redemption = db.collection("rewardRedemptions").doc(); await db.runTransaction(async (transaction) => { const [reward, current] = await Promise.all([transaction.get(rewardRef), transaction.get(walletRef)]); if (!reward.exists || reward.get("active") !== true) throw new ApiError(404, "Active reward not found.", "not_found"); const cost = number(reward.get("pointsCost")) * input.quantity; if (number(reward.get("stock")) < input.quantity) throw new ApiError(409, "Reward stock is insufficient.", "insufficient_stock"); if (number(current.get("balance")) < cost) throw new ApiError(409, "Green point balance is insufficient.", "insufficient_points"); const couponCode = `${reward.get("couponPrefix")}-${redemption.id.substring(0, 8).toUpperCase()}`; transaction.update(rewardRef, {stock: FieldValue.increment(-input.quantity), updatedAt: FieldValue.serverTimestamp()}); transaction.update(walletRef, {balance: FieldValue.increment(-cost), lifetimeRedeemed: FieldValue.increment(cost), updatedAt: FieldValue.serverTimestamp()}); transaction.set(redemption, {...input, userId: request.user!.uid, rewardName: reward.get("name"), partnerId: reward.get("partnerId") ?? "", pointsSpent: cost, couponCode, status: "issued", createdAt: FieldValue.serverTimestamp()}); transaction.set(walletRef.collection("transactions").doc(), {type: "debit", points: -cost, referenceId: redemption.id, description: `Redeemed ${reward.get("name")}`, status: "completed", createdAt: FieldValue.serverTimestamp()}); }); void publishNotificationEvent({event: "reward_redeemed", recipientId: request.user!.uid, data: {redemptionId: redemption.id}}); response.status(201).json({data: {id: redemption.id, status: "issued"}}); });

router.post("/rewards/fraud-flags", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({userId: z.string().trim().min(1), type: z.enum(["duplicatePickup", "selfReferral", "velocity", "locationMismatch", "manualReview", "other"]), severity: z.enum(["low", "medium", "high", "critical"]), referenceIds: z.array(z.string().trim().min(1)).min(1), description: z.string().trim().min(2).max(2000)}).parse(request.body); const ref = await db.collection("rewardFraudFlags").add({...input, status: "open", reportedBy: request.user!.uid, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.status(201).json({data: {id: ref.id}}); });
router.get("/rewards/fraud-flags", authenticate, requireRoles(...managers), async (_request, response) => { const snapshot = await db.collection("rewardFraudFlags").limit(500).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.patch("/rewards/fraud-flags/:id", authenticate, requireRoles(...managers), async (request, response) => { const input = z.object({status: z.enum(["open", "investigating", "confirmed", "dismissed"]), resolution: z.string().trim().max(2000).default("")}).parse(request.body); const ref = db.collection("rewardFraudFlags").doc(id(request.params.id)); if (!(await ref.get()).exists) throw new ApiError(404, "Fraud flag not found.", "not_found"); await ref.update({...input, reviewedBy: request.user!.uid, reviewedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: ref.id, status: input.status}}); });

router.get("/rewards/leaderboard", authenticate, requireRoles(...users), async (request, response) => { const limit = z.coerce.number().int().min(1).max(100).default(20).parse(request.query.limit); const snapshot = await db.collection("rewardWallets").orderBy("lifetimeEarned", "desc").limit(limit).get(); response.json({data: snapshot.docs.map((doc, index) => ({rank: index + 1, ...documentJson(doc.id, doc.data())}))}); });

router.get("/rewards/business-score/:userId", authenticate, requireRoles(...users), async (request, response) => { const userId = id(request.params.userId); if (userId !== request.user!.uid && !["administrator", "superAdministrator"].includes(request.user!.role)) throw new ApiError(403, "You cannot access this sustainability score.", "forbidden"); const [walletSnapshot, pickups, donations] = await Promise.all([db.collection("rewardWallets").doc(userId).get(), db.collection("pickupRequests").where("userId", "==", userId).limit(500).get(), db.collection("donationRequests").where("requestedBy", "==", userId).limit(500).get()]); const recycledKg = pickups.docs.filter((doc) => ["completed", "collected"].includes(String(doc.get("status")))).reduce((sum, doc) => sum + number(doc.get("actualWeight") ?? doc.get("estimatedWeight")), 0); const completedPickups = pickups.docs.filter((doc) => ["completed", "collected"].includes(String(doc.get("status")))).length; const devicesDonated = donations.docs.filter((doc) => doc.get("status") === "confirmed").reduce((sum, doc) => sum + number(doc.get("allocatedQuantity")), 0); const score = Math.min(100, recycledKg * 0.2 + completedPickups * 2 + devicesDonated * 3 + number(walletSnapshot.get("lifetimeEarned")) * 0.005); response.json({data: {userId, score, recycledKg, completedPickups, devicesDonated, level: level(number(walletSnapshot.get("lifetimeEarned")))}}); });

router.get("/rewards/certificate", authenticate, requireRoles(...users), async (request, response) => { const current = await wallet(request.user!.uid); if (!current.snapshot.exists || number(current.snapshot.get("lifetimeEarned")) < 100) throw new ApiError(409, "Earn at least 100 green points to generate a certificate.", "insufficient_points"); response.json({data: {certificateNumber: `GREEN-${request.user!.uid.substring(0, 8).toUpperCase()}-${new Date().getUTCFullYear()}`, issuedAt: new Date().toISOString(), userId: request.user!.uid, lifetimeGreenPoints: current.snapshot.get("lifetimeEarned"), level: current.snapshot.get("level")}}); });

router.get("/rewards/reports/summary", authenticate, requireRoles(...managers), async (_request, response) => { const [wallets, redemptions, fraud, challenges] = await Promise.all([db.collection("rewardWallets").limit(1000).get(), db.collection("rewardRedemptions").limit(1000).get(), db.collection("rewardFraudFlags").limit(1000).get(), db.collection("rewardChallenges").limit(1000).get()]); let issued = 0; let redeemed = 0; const byLevel: Record<string, number> = {}; for (const doc of wallets.docs) { issued += number(doc.get("lifetimeEarned")); redeemed += number(doc.get("lifetimeRedeemed")); const userLevel = String(doc.get("level") ?? "greenStarter"); byLevel[userLevel] = (byLevel[userLevel] ?? 0) + 1; } response.json({data: {wallets: wallets.size, pointsIssued: issued, pointsRedeemed: redeemed, pointsOutstanding: issued - redeemed, redemptions: redemptions.size, openFraudFlags: fraud.docs.filter((doc) => doc.get("status") === "open").length, activeChallenges: challenges.docs.filter((doc) => doc.get("active") === true).length, byLevel}}); });

export default router;
