import {Router} from "express";
import {FieldValue} from "firebase-admin/firestore";
import {z} from "zod";
import {authenticate, requireRoles} from "./auth.js";
import {ApiError} from "./errors.js";
import {db} from "./firebase.js";
import {documentJson} from "./firestore-json.js";

const router = Router(); const users = ["household", "business", "institution", "collector", "driver", "collectionCentreOperator", "repairTechnician", "recycler", "environmentalOfficer", "administrator", "superAdministrator"] as const; const agents = ["environmentalOfficer", "administrator", "superAdministrator"] as const;
const categories = ["pickup", "payment", "marketplace", "rewards", "account", "collectionCentre", "repair", "recycling", "safety", "technical", "serviceDispute", "pickupService", "damagedItem", "billingOrFee", "repairService", "recyclingService", "staffConduct", "dataPrivacy", "technicalIssue", "other"] as const;
function id(value: string | string[]) { return Array.isArray(value) ? value[0] : value; }
async function ticketRecord(ticketId: string) { const ref = db.collection("supportTickets").doc(ticketId); const snapshot = await ref.get(); if (!snapshot.exists) throw new ApiError(404, "Support ticket not found.", "not_found"); return {ref, snapshot}; }
function access(data: FirebaseFirestore.DocumentData, uid: string, role: string) { return ["environmentalOfficer", "administrator", "superAdministrator"].includes(role) || data.userId === uid; }

router.post("/support/tickets", authenticate, requireRoles(...users), async (request, response) => { const input = z.object({category: z.enum(categories), subject: z.string().trim().min(2).max(300), description: z.string().trim().min(5).max(5000), priority: z.enum(["low", "normal", "high", "urgent"]).default("normal"), evidenceUrls: z.array(z.string().url()).max(10).default([]), referenceType: z.string().trim().max(100).default(""), referenceId: z.string().trim().max(200).default(""), userName: z.string().trim().max(200).default("")}).parse(request.body); const ref = db.collection("supportTickets").doc(); const message = ref.collection("messages").doc(); const batch = db.batch(); batch.set(ref, {...input, ticketNumber: `SUP-${ref.id.substring(0, 10).toUpperCase()}`, userId: request.user!.uid, userEmail: request.user!.email ?? "", agentId: "", agentName: "", assignedAgentId: "", status: "submitted", escalationLevel: 0, escalationReason: "", resolution: "", satisfactionRating: 0, satisfactionComment: "", createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); batch.set(message, {senderId: request.user!.uid, senderName: input.userName || "User", senderType: "user", internal: false, body: input.description, attachmentUrls: input.evidenceUrls, createdAt: FieldValue.serverTimestamp()}); await batch.commit(); response.status(201).json({data: {id: ref.id, ticketNumber: `SUP-${ref.id.substring(0, 10).toUpperCase()}`}}); });
router.get("/support/tickets", authenticate, requireRoles(...users), async (request, response) => { const privileged = ["environmentalOfficer", "administrator", "superAdministrator"].includes(request.user!.role); let query: FirebaseFirestore.Query = privileged ? db.collection("supportTickets") : db.collection("supportTickets").where("userId", "==", request.user!.uid); if (typeof request.query.status === "string") query = query.where("status", "==", request.query.status); if (typeof request.query.priority === "string") query = query.where("priority", "==", request.query.priority); const snapshot = await query.limit(500).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.get("/support/tickets/:id", authenticate, requireRoles(...users), async (request, response) => { const ticket = await ticketRecord(id(request.params.id)); if (!access(ticket.snapshot.data()!, request.user!.uid, request.user!.role)) throw new ApiError(403, "You cannot access this ticket.", "forbidden"); response.json({data: documentJson(ticket.snapshot.id, ticket.snapshot.data()!)}); });
router.patch("/support/tickets/:id/assignment", authenticate, requireRoles(...agents), async (request, response) => { const input = z.object({agentId: z.string().trim().min(1), priority: z.enum(["low", "normal", "high", "urgent"]).optional()}).parse(request.body); const ticket = await ticketRecord(id(request.params.id)); if (["resolved", "closed"].includes(String(ticket.snapshot.get("status")))) throw new ApiError(409, "Closed tickets cannot be reassigned.", "invalid_state"); const agent = await db.collection("users").doc(input.agentId).get(); if (!agent.exists || !["environmentalOfficer", "administrator", "superAdministrator"].includes(String(agent.get("role")))) throw new ApiError(409, "Select an active support agent.", "invalid_agent"); await ticket.ref.update({agentId: input.agentId, agentName: String(agent.get("displayName") ?? agent.get("email") ?? input.agentId), assignedAgentId: input.agentId, ...(input.priority ? {priority: input.priority} : {}), status: "assigned", assignedBy: request.user!.uid, assignedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: ticket.ref.id, assignedAgentId: input.agentId, status: "assigned"}}); });
router.patch("/support/tickets/:id/status", authenticate, requireRoles(...agents), async (request, response) => { const input = z.object({status: z.enum(["open", "assigned", "inProgress", "waitingForUser", "escalated", "resolved", "closed"]), notes: z.string().trim().max(1000).default("")}).parse(request.body); const ticket = await ticketRecord(id(request.params.id)); await ticket.ref.update({status: input.status, statusNotes: input.notes, statusChangedBy: request.user!.uid, statusChangedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), ...(input.status === "closed" ? {closedAt: FieldValue.serverTimestamp()} : {})}); response.json({data: {id: ticket.ref.id, status: input.status}}); });
router.post("/support/tickets/:id/messages", authenticate, requireRoles(...users), async (request, response) => { const input = z.object({body: z.string().trim().min(1).max(5000), attachmentUrls: z.array(z.string().url()).max(10).default([]), senderName: z.string().trim().max(200).default("")}).parse(request.body); const ticket = await ticketRecord(id(request.params.id)); if (!access(ticket.snapshot.data()!, request.user!.uid, request.user!.role)) throw new ApiError(403, "You cannot message this ticket.", "forbidden"); if (ticket.snapshot.get("status") === "closed") throw new ApiError(409, "Closed tickets cannot receive messages.", "invalid_state"); const agent = ["environmentalOfficer", "administrator", "superAdministrator"].includes(request.user!.role); const ref = ticket.ref.collection("messages").doc(); const batch = db.batch(); batch.set(ref, {...input, senderId: request.user!.uid, senderName: input.senderName || (agent ? "Support team" : "User"), senderType: agent ? "agent" : "user", internal: false, createdAt: FieldValue.serverTimestamp()}); batch.update(ticket.ref, {status: agent ? "waitingForUser" : "inProgress", lastMessageAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); await batch.commit(); response.status(201).json({data: {id: ref.id}}); });
router.get("/support/tickets/:id/messages", authenticate, requireRoles(...users), async (request, response) => { const ticket = await ticketRecord(id(request.params.id)); if (!access(ticket.snapshot.data()!, request.user!.uid, request.user!.role)) throw new ApiError(403, "You cannot access these messages.", "forbidden"); const snapshot = await ticket.ref.collection("messages").orderBy("createdAt", "asc").limit(500).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.post("/support/tickets/:id/internal-notes", authenticate, requireRoles(...agents), async (request, response) => { const input = z.object({note: z.string().trim().min(2).max(3000)}).parse(request.body); const ticket = await ticketRecord(id(request.params.id)); const ref = await ticket.ref.collection("internalNotes").add({...input, authorId: request.user!.uid, createdAt: FieldValue.serverTimestamp()}); response.status(201).json({data: {id: ref.id}}); });
router.get("/support/tickets/:id/internal-notes", authenticate, requireRoles(...agents), async (request, response) => { const ticket = await ticketRecord(id(request.params.id)); const snapshot = await ticket.ref.collection("internalNotes").orderBy("createdAt", "asc").limit(500).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.patch("/support/tickets/:id/escalate", authenticate, requireRoles(...agents), async (request, response) => { const input = z.object({level: z.number().int().min(1).max(3), reason: z.string().trim().min(2).max(2000), escalateToAgentId: z.string().trim().max(200).default("")}).parse(request.body); const ticket = await ticketRecord(id(request.params.id)); if (input.level <= Number(ticket.snapshot.get("escalationLevel") ?? 0)) throw new ApiError(409, "Escalation level must increase.", "invalid_level"); await ticket.ref.update({status: "escalated", escalationLevel: input.level, escalationReason: input.reason, ...(input.escalateToAgentId ? {assignedAgentId: input.escalateToAgentId} : {}), escalatedBy: request.user!.uid, escalatedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: ticket.ref.id, status: "escalated", escalationLevel: input.level}}); });
router.patch("/support/tickets/:id/resolve", authenticate, requireRoles(...agents), async (request, response) => { const input = z.object({resolution: z.string().trim().min(5).max(5000), outcome: z.enum(["resolved", "refundIssued", "serviceRepeated", "userEducated", "rejected", "other"])}).parse(request.body); const ticket = await ticketRecord(id(request.params.id)); await ticket.ref.update({...input, status: "resolved", resolvedBy: request.user!.uid, resolvedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: ticket.ref.id, status: "resolved"}}); });
router.patch("/support/tickets/:id/rating", authenticate, requireRoles(...users), async (request, response) => { const input = z.object({rating: z.number().int().min(1).max(5), comments: z.string().trim().max(1000).default("")}).parse(request.body); const ticket = await ticketRecord(id(request.params.id)); if (ticket.snapshot.get("userId") !== request.user!.uid) throw new ApiError(403, "Only the ticket owner can rate support.", "forbidden"); if (ticket.snapshot.get("status") !== "resolved") throw new ApiError(409, "Resolve the ticket before rating support.", "invalid_state"); if (ticket.snapshot.get("satisfactionRating")) throw new ApiError(409, "This ticket is already rated.", "conflict"); await ticket.ref.update({satisfactionRating: input.rating, satisfactionComments: input.comments, ratedAt: FieldValue.serverTimestamp(), status: "closed", closedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: ticket.ref.id, rating: input.rating}}); });
router.patch("/support/tickets/:id/reopen", authenticate, requireRoles(...users), async (request, response) => { const input = z.object({reason: z.string().trim().min(2).max(1000).default("Issue not resolved")}).parse(request.body); const ticket = await ticketRecord(id(request.params.id)); if (ticket.snapshot.get("userId") !== request.user!.uid) throw new ApiError(403, "Only the ticket owner can reopen support.", "forbidden"); if (!["resolved", "closed"].includes(String(ticket.snapshot.get("status")))) throw new ApiError(409, "Only resolved or closed tickets can be reopened.", "invalid_state"); await ticket.ref.update({status: "reopened", reopenReason: input.reason, reopenedBy: request.user!.uid, reopenedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp()}); response.json({data: {id: ticket.ref.id, status: "reopened"}}); });

router.get("/support/knowledge-base", async (request, response, next) => { const wantsDrafts = request.query.includeDrafts === "true"; if (wantsDrafts) { try { await new Promise<void>((resolve, reject) => authenticate(request, response, (error?: unknown) => (error ? reject(error) : resolve()))); } catch (error) { next(error); return; } if (!agents.includes(request.user!.role as typeof agents[number])) { next(new ApiError(403, "Only support agents can view draft articles.", "forbidden")); return; } } let query: FirebaseFirestore.Query = db.collection("supportKnowledgeBase"); if (!wantsDrafts) query = query.where("published", "==", true); if (typeof request.query.category === "string") query = query.where("category", "==", request.query.category); const snapshot = await query.limit(300).get(); const search = typeof request.query.search === "string" ? request.query.search.toLowerCase() : ""; response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data())).filter((article) => !search || `${article.title} ${article.content}`.toLowerCase().includes(search))}); });
router.put("/support/knowledge-base/:id", authenticate, requireRoles(...agents), async (request, response) => { const input = z.object({title: z.string().trim().min(2).max(300), category: z.string().trim().min(2).max(100), content: z.string().trim().min(10).max(20000), type: z.enum(["faq", "guide", "policy"]).default("faq"), tags: z.array(z.string().trim().min(1).max(100)).default([]), published: z.boolean()}).parse(request.body); const articleId = id(request.params.id); await db.collection("supportKnowledgeBase").doc(articleId).set({...input, viewCount: FieldValue.increment(0), updatedBy: request.user!.uid, updatedAt: FieldValue.serverTimestamp()}, {merge: true}); response.json({data: {id: articleId}}); });
router.post("/support/knowledge-base/:id/view", async (request, response) => { const ref = db.collection("supportKnowledgeBase").doc(id(request.params.id)); if (!(await ref.get()).exists) throw new ApiError(404, "Article not found.", "not_found"); await ref.update({viewCount: FieldValue.increment(1)}); response.json({data: {id: ref.id}}); });
router.get("/support/agents", authenticate, requireRoles(...agents), async (_request, response) => { const snapshot = await db.collection("users").where("role", "in", ["environmentalOfficer", "administrator", "superAdministrator"]).limit(300).get(); response.json({data: snapshot.docs.map((doc) => documentJson(doc.id, doc.data()))}); });
router.get("/support/reports/summary", authenticate, requireRoles(...agents), async (_request, response) => { const snapshot = await db.collection("supportTickets").limit(2000).get(); const byStatus: Record<string, number> = {}; const byCategory: Record<string, number> = {}; let ratings = 0; let rated = 0; let resolved = 0; for (const doc of snapshot.docs) { const status = String(doc.get("status") ?? "unknown"); const category = String(doc.get("category") ?? "other"); byStatus[status] = (byStatus[status] ?? 0) + 1; byCategory[category] = (byCategory[category] ?? 0) + 1; if (["resolved", "closed"].includes(status)) resolved++; if (doc.get("satisfactionRating")) {ratings += Number(doc.get("satisfactionRating")); rated++;} } response.json({data: {tickets: snapshot.size, resolvedTickets: resolved, resolutionRate: snapshot.size ? resolved / snapshot.size * 100 : 0, averageSatisfaction: rated ? ratings / rated : 0, escalatedTickets: byStatus.escalated ?? 0, byStatus, byCategory}}); });

export default router;
