// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGK7r7U3dzAaWR3cFzBmG2rMO4tQX7i5g',
    appId: '1:900123114350:web:23b7ccb9629b7e48efdf7f',
    messagingSenderId: '900123114350',
    projectId: 'wastemanagementsystem-902eb',
    authDomain: 'wastemanagementsystem-902eb.firebaseapp.com',
    storageBucket: 'wastemanagementsystem-902eb.firebasestorage.app',
    measurementId: 'G-N0ZT6896V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2VUiudpwaaJ3mcxspYPC2ZtvvaiTj0K8',
    appId: '1:900123114350:android:b84a9ceb2800b4a2efdf7f',
    messagingSenderId: '900123114350',
    projectId: 'wastemanagementsystem-902eb',
    storageBucket: 'wastemanagementsystem-902eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxKAckG9yGB9qRYX5ePYoDalaj23hlcBM',
    appId: '1:900123114350:ios:7f069b36689bc5bfefdf7f',
    messagingSenderId: '900123114350',
    projectId: 'wastemanagementsystem-902eb',
    storageBucket: 'wastemanagementsystem-902eb.firebasestorage.app',
    iosBundleId: 'com.example.wastemanagementsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxKAckG9yGB9qRYX5ePYoDalaj23hlcBM',
    appId: '1:900123114350:ios:7f069b36689bc5bfefdf7f',
    messagingSenderId: '900123114350',
    projectId: 'wastemanagementsystem-902eb',
    storageBucket: 'wastemanagementsystem-902eb.firebasestorage.app',
    iosBundleId: 'com.example.wastemanagementsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGK7r7U3dzAaWR3cFzBmG2rMO4tQX7i5g',
    appId: '1:900123114350:web:18a4086954b86088efdf7f',
    messagingSenderId: '900123114350',
    projectId: 'wastemanagementsystem-902eb',
    authDomain: 'wastemanagementsystem-902eb.firebaseapp.com',
    storageBucket: 'wastemanagementsystem-902eb.firebasestorage.app',
    measurementId: 'G-PP7PM12WRK',
  );
}
