"""Authenticated HTTP routes for token management and FCM delivery."""

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status

from app.notifications.schemas import (
    AdminMessageRequest,
    AnnouncementRequest,
    EventNotificationRequest,
    NotificationRecord,
    NotificationType,
    RegisterTokenRequest,
    RemoveTokenRequest,
    SendNotificationRequest,
    SendResult,
)
from app.notifications.service import NotificationService
from app.notifications.utils import ADMIN_ROLES, CurrentUser, admin_user, current_user, event_authorized

router = APIRouter(prefix="/notifications", tags=["notifications"])


def notification_service() -> NotificationService:
    """Dependency-injected service factory."""
    return NotificationService()


Service = Annotated[NotificationService, Depends(notification_service)]
User = Annotated[CurrentUser, Depends(current_user)]
Admin = Annotated[CurrentUser, Depends(admin_user)]


@router.post("/register-token", status_code=status.HTTP_201_CREATED)
def register_token(payload: RegisterTokenRequest, user: User, service: Service) -> dict[str, str]:
    """Register or refresh the caller's FCM token."""
    if payload.user_id and payload.user_id != user.uid and user.role not in ADMIN_ROLES:
        raise HTTPException(status.HTTP_403_FORBIDDEN, "A token can only be registered for your own account.")
    user_id = payload.user_id if payload.user_id and user.role in ADMIN_ROLES else user.uid
    return {"id": service.register_token(user_id, payload.device_token, payload.platform.value), "status": "registered"}


@router.delete("/remove-token", status_code=status.HTTP_204_NO_CONTENT)
def remove_token(payload: RemoveTokenRequest, user: User, service: Service) -> Response:
    """Delete the caller's FCM registration during logout."""
    service.remove_token(user.uid, payload.device_token)
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@router.post("/send", response_model=SendResult)
def send_notification(payload: SendNotificationRequest, _admin: Admin, service: Service) -> SendResult:
    """Send a typed notification to one selected user."""
    return service.send_to_user(payload.user_id, payload.title, payload.body, payload.type, payload.data)


@router.post("/send-admin-message", response_model=SendResult)
def send_admin_message(payload: AdminMessageRequest, _admin: Admin, service: Service) -> SendResult:
    """Send an administrator message to selected users."""
    return service.send_to_multiple_users(payload.user_ids, payload.title, payload.body, NotificationType.ADMIN_MESSAGE, payload.data)


@router.post("/send-announcement", response_model=SendResult)
def send_announcement(payload: AnnouncementRequest, _admin: Admin, service: Service) -> SendResult:
    """Broadcast an announcement to all active EcoTrace users."""
    return service.send_announcement(payload.title, payload.body, payload.data, payload.topic)


@router.post("/events", response_model=SendResult, dependencies=[Depends(event_authorized)])
def send_event(payload: EventNotificationRequest, service: Service) -> SendResult:
    """Send a trusted notification generated by a backend domain event."""
    return service.notify_event(payload.event, payload.recipient_id, payload.affected_user_ids, payload.body, payload.data)


@router.get("/user/{user_id}", response_model=list[NotificationRecord])
def user_notifications(user_id: str, user: User, service: Service, limit: int = Query(default=100, ge=1, le=500)) -> list[dict]:
    """Return notification history for the owner or an administrator."""
    if user.uid != user_id and user.role not in ADMIN_ROLES:
        raise HTTPException(status.HTTP_403_FORBIDDEN, "You cannot read another user's notifications.")
    return service.list_history(user_id, limit)


@router.patch("/{notification_id}/read", status_code=status.HTTP_204_NO_CONTENT)
def mark_notification_read(notification_id: str, user: User, service: Service) -> Response:
    """Mark an owned notification as read."""
    try:
        service.mark_read(notification_id, user.uid, user.role in ADMIN_ROLES)
    except KeyError as exc:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Notification not found.") from exc
    except PermissionError as exc:
        raise HTTPException(status.HTTP_403_FORBIDDEN, "You cannot update this notification.") from exc
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@router.delete("/{notification_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_notification(notification_id: str, user: User, service: Service) -> Response:
    """Delete an owned notification."""
    try:
        service.delete_notification(notification_id, user.uid, user.role in ADMIN_ROLES)
    except KeyError as exc:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Notification not found.") from exc
    except PermissionError as exc:
        raise HTTPException(status.HTTP_403_FORBIDDEN, "You cannot delete this notification.") from exc
    return Response(status_code=status.HTTP_204_NO_CONTENT)
