import 'package:flutter/material.dart';
import '../../inventory/domain/inventory_item.dart';
import '../data/assessment_repository.dart';
import '../domain/assessment.dart';

class AssessmentScreen extends StatefulWidget {
  const AssessmentScreen({
    super.key,
    required this.item,
    required this.repository,
    required this.canApprove,
  });
  final InventoryItem item;
  final AssessmentRepository repository;
  final bool canApprove;
  @override
  State<AssessmentScreen> createState() => _AssessmentState();
}

class _AssessmentState extends State<AssessmentScreen> {
  DeviceCategory category = DeviceCategory.accessories;
  TreatmentRecommendation recommendation = TreatmentRecommendation.recycle;
  late ItemCondition assessedCondition;
  final materials = TextEditingController(
        text: 'metals:45, plastics:30, glass:15, other:10',
      ),
      hazards = TextEditingController(),
      value = TextEditingController(text: '0'),
      notes = TextEditingController();
  double reuse = 50, repair = 50, confidence = .5;
  bool busy = false, assisted = false;

  @override
  void initState() {
    super.initState();
    assessedCondition = widget.item.condition;
  }

  @override
  void dispose() {
    materials.dispose();
    hazards.dispose();
    value.dispose();
    notes.dispose();
    super.dispose();
  }

  Future<void> _assist() async {
    setState(() => busy = true);
    try {
      final response = await widget.repository.assistedSuggestion(widget.item);
      final x = response['suggestion'] is Map
          ? Map<String, dynamic>.from(response['suggestion'] as Map)
          : response;
      if (!mounted) return;
      setState(() {
        category = x['category'] is DeviceCategory
            ? x['category'] as DeviceCategory
            : DeviceCategory.values.byName(x['category'].toString());
        assessedCondition = ItemCondition.values.byName(
          x['assessedCondition']?.toString() ?? widget.item.condition.name,
        );
        hazards.text = List<String>.from(x['hazards'] ?? const []).join(', ');
        confidence = (x['confidence'] as num? ?? .5).toDouble();
        reuse = (x['reusability'] as num? ?? 50).toDouble();
        repair = (x['repairability'] as num? ?? 50).toDouble();
        recommendation = TreatmentRecommendation.values.byName(
          x['recommendation']?.toString() ?? 'recycle',
        );
        value.text = (x['recoveryValue'] as num? ?? 0).toStringAsFixed(2);
        final composition = (x['materials'] as Map? ?? const {}).map(
          (key, value) => MapEntry(key.toString(), (value as num).toDouble()),
        );
        materials.text = composition.entries
            .map((e) => '${e.key}:${e.value}')
            .join(', ');
        assisted = true;
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'Suggestion generated by ${response['engine'] ?? 'classification engine'}. Verify before submitting.',
          ),
        ),
      );
    } catch (error) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Unable to classify item: $error')),
        );
      }
    } finally {
      if (mounted) setState(() => busy = false);
    }
  }

  Map<String, double> _materials() => {
    for (final part in materials.text.split(','))
      if (part.contains(':'))
        part.split(':').first.trim():
            double.tryParse(part.split(':').last.trim()) ?? 0,
  };
  Future<void> _submit() async {
    final composition = _materials();
    final total = composition.values.fold<double>(0, (sum, item) => sum + item);
    final hazardList = hazards.text
        .split(',')
        .map((x) => x.trim())
        .where((x) => x.isNotEmpty)
        .toList();
    if (composition.isEmpty || (total - 100).abs() > 1) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Material percentages must total 100% (±1%).'),
        ),
      );
      return;
    }
    if (recommendation == TreatmentRecommendation.hazardousDisposal &&
        hazardList.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Identify at least one hazard for hazardous disposal.'),
        ),
      );
      return;
    }
    setState(() => busy = true);
    try {
      await widget.repository.submit(
        item: widget.item,
        category: category,
        materials: composition,
        hazards: hazardList,
        reusability: reuse.round(),
        repairability: repair.round(),
        recommendation: recommendation,
        assessedCondition: assessedCondition,
        origin: assisted
            ? AssessmentOrigin.aiAssisted
            : AssessmentOrigin.manual,
        recoveryValue: double.tryParse(value.text) ?? 0,
        confidence: confidence,
        notes: notes.text,
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Assessment submitted for approval.')),
        );
      }
    } catch (error) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Unable to submit assessment: $error')),
        );
      }
    } finally {
      if (mounted) setState(() => busy = false);
    }
  }

  @override
  Widget build(BuildContext c) => Scaffold(
    appBar: AppBar(
      title: Text('Assessment • ${widget.item.itemCode}'),
      actions: [
        if (widget.canApprove)
          IconButton(
            tooltip: 'Supervisor review queue',
            onPressed: () => Navigator.push(
              c,
              MaterialPageRoute(
                builder: (_) => ClassificationReviewQueueScreen(
                  repository: widget.repository,
                ),
              ),
            ),
            icon: const Icon(Icons.fact_check_outlined),
          ),
      ],
    ),
    body: ListView(
      padding: const EdgeInsets.all(16),
      children: [
        FutureBuilder<ClassificationSummary>(
          future: widget.repository.summary(),
          builder: (context, snapshot) {
            final summary = snapshot.data;
            if (summary == null) return const LinearProgressIndicator();
            return Card(
              child: Padding(
                padding: const EdgeInsets.all(12),
                child: Wrap(
                  spacing: 24,
                  runSpacing: 8,
                  children: [
                    Text('${summary.totalAssessments} assessments'),
                    Text(
                      '${(summary.averageConfidence * 100).toStringAsFixed(0)}% avg. confidence',
                    ),
                    Text(
                      '${summary.byStatus['pendingSupervisor'] ?? 0} awaiting review',
                    ),
                  ],
                ),
              ),
            );
          },
        ),
        OutlinedButton.icon(
          onPressed: busy ? null : _assist,
          icon: const Icon(Icons.auto_awesome),
          label: const Text('Generate assisted classification'),
        ),
        DropdownButtonFormField(
          initialValue: category,
          decoration: const InputDecoration(labelText: 'Device category'),
          items: DeviceCategory.values
              .map((x) => DropdownMenuItem(value: x, child: Text(x.name)))
              .toList(),
          onChanged: (x) => setState(() => category = x!),
        ),
        const SizedBox(height: 12),
        DropdownButtonFormField(
          initialValue: assessedCondition,
          decoration: const InputDecoration(labelText: 'Assessed condition'),
          items: ItemCondition.values
              .map((x) => DropdownMenuItem(value: x, child: Text(x.name)))
              .toList(),
          onChanged: (x) => setState(() => assessedCondition = x!),
        ),
        const SizedBox(height: 12),
        TextField(
          controller: materials,
          maxLines: 2,
          decoration: const InputDecoration(
            labelText: 'Material composition (%)',
          ),
        ),
        const SizedBox(height: 12),
        TextField(
          controller: hazards,
          maxLines: 2,
          decoration: const InputDecoration(labelText: 'Hazardous components'),
        ),
        Text('Reusability: ${reuse.round()}%'),
        Slider(
          value: reuse,
          max: 100,
          onChanged: (x) => setState(() => reuse = x),
        ),
        Text('Repairability: ${repair.round()}%'),
        Slider(
          value: repair,
          max: 100,
          onChanged: (x) => setState(() => repair = x),
        ),
        DropdownButtonFormField(
          initialValue: recommendation,
          decoration: const InputDecoration(
            labelText: 'Treatment recommendation',
          ),
          items: TreatmentRecommendation.values
              .map((x) => DropdownMenuItem(value: x, child: Text(x.name)))
              .toList(),
          onChanged: (x) => setState(() => recommendation = x!),
        ),
        const SizedBox(height: 12),
        TextField(
          controller: value,
          keyboardType: TextInputType.number,
          decoration: const InputDecoration(
            labelText: 'Estimated recovery value (SLE)',
          ),
        ),
        Text('Confidence: ${(confidence * 100).round()}%'),
        Slider(
          value: confidence,
          onChanged: (x) => setState(() => confidence = x),
        ),
        TextField(
          controller: notes,
          maxLines: 3,
          decoration: const InputDecoration(labelText: 'Assessment notes'),
        ),
        const SizedBox(height: 12),
        FilledButton(
          onPressed: busy ? null : _submit,
          child: const Text('Submit assessment'),
        ),
        const Divider(height: 32),
        Text('Assessment history', style: Theme.of(c).textTheme.titleLarge),
        StreamBuilder<List<ItemAssessment>>(
          stream: widget.repository.watch(widget.item.id),
          builder: (c, s) => Column(
            children: (s.data ?? [])
                .map(
                  (a) => Card(
                    child: ListTile(
                      title: Text(
                        '${a.category.name} • ${a.recommendation.name}',
                      ),
                      subtitle: Text(
                        '${a.status.name} • version ${a.version} • ${a.origin.name} • confidence ${(a.confidence * 100).round()}% • SLE ${a.recoveryValue.toStringAsFixed(2)}'
                        '${a.reviewReason == null ? '' : '\n${a.reviewReason}'}',
                      ),
                      trailing:
                          widget.canApprove &&
                              a.status == AssessmentStatus.pendingSupervisor
                          ? PopupMenuButton<bool>(
                              onSelected: (approved) => _review(a, approved),
                              itemBuilder: (_) => const [
                                PopupMenuItem(
                                  value: true,
                                  child: Text('Approve'),
                                ),
                                PopupMenuItem(
                                  value: false,
                                  child: Text('Reject'),
                                ),
                              ],
                            )
                          : null,
                      onTap: a.status == AssessmentStatus.pendingSupervisor
                          ? () => _editPending(a)
                          : null,
                    ),
                  ),
                )
                .toList(),
          ),
        ),
      ],
    ),
  );

  Future<void> _review(ItemAssessment assessment, bool approved) async {
    String? reason;
    if (!approved) {
      final controller = TextEditingController();
      reason = await showDialog<String>(
        context: context,
        builder: (context) => AlertDialog(
          title: const Text('Reject assessment'),
          content: TextField(
            controller: controller,
            maxLength: 1000,
            decoration: const InputDecoration(labelText: 'Rejection reason'),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Cancel'),
            ),
            FilledButton(
              onPressed: () => Navigator.pop(context, controller.text.trim()),
              child: const Text('Reject'),
            ),
          ],
        ),
      );
      controller.dispose();
      if (reason == null || reason.trim().isEmpty) return;
    }
    await widget.repository.review(
      widget.item.id,
      assessment.id,
      approved: approved,
      reason: reason,
    );
  }

  Future<void> _editPending(ItemAssessment assessment) async {
    final notesController = TextEditingController(text: assessment.notes);
    final valueController = TextEditingController(
      text: assessment.recoveryValue.toStringAsFixed(2),
    );
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Edit assessment v${assessment.version}'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              controller: valueController,
              keyboardType: TextInputType.number,
              decoration: const InputDecoration(
                labelText: 'Recovery value (SLE)',
              ),
            ),
            TextField(
              controller: notesController,
              maxLines: 3,
              decoration: const InputDecoration(labelText: 'Notes'),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () => Navigator.pop(context, true),
            child: const Text('Save'),
          ),
        ],
      ),
    );
    final recoveryValue = double.tryParse(valueController.text);
    if (confirmed == true && recoveryValue != null && recoveryValue >= 0) {
      await widget.repository.update(
        widget.item.id,
        assessment,
        notes: notesController.text,
        recoveryValue: recoveryValue,
      );
    }
    notesController.dispose();
    valueController.dispose();
  }
}

class ClassificationReviewQueueScreen extends StatefulWidget {
  const ClassificationReviewQueueScreen({super.key, required this.repository});
  final AssessmentRepository repository;

  @override
  State<ClassificationReviewQueueScreen> createState() =>
      _ClassificationReviewQueueScreenState();
}

class _ClassificationReviewQueueScreenState
    extends State<ClassificationReviewQueueScreen> {
  late Future<List<ItemAssessment>> _queue;

  @override
  void initState() {
    super.initState();
    _reload();
  }

  void _reload() => _queue = widget.repository.reviewQueue();

  Future<void> _review(ItemAssessment assessment, bool approved) async {
    String? reason;
    if (!approved) {
      final controller = TextEditingController();
      reason = await showDialog<String>(
        context: context,
        builder: (context) => AlertDialog(
          title: const Text('Reject assessment'),
          content: TextField(
            controller: controller,
            maxLength: 1000,
            decoration: const InputDecoration(labelText: 'Rejection reason'),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Cancel'),
            ),
            FilledButton(
              onPressed: () => Navigator.pop(context, controller.text.trim()),
              child: const Text('Reject'),
            ),
          ],
        ),
      );
      controller.dispose();
      if (reason == null || reason.trim().isEmpty) return;
    }
    await widget.repository.review(
      assessment.itemId,
      assessment.id,
      approved: approved,
      reason: reason,
    );
    if (mounted) setState(_reload);
  }

  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(title: const Text('Classification review queue')),
    body: FutureBuilder<List<ItemAssessment>>(
      future: _queue,
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          return Center(
            child: Text('Unable to load review queue: ${snapshot.error}'),
          );
        }
        if (!snapshot.hasData) {
          return const Center(child: CircularProgressIndicator());
        }
        final assessments = snapshot.data!;
        if (assessments.isEmpty) {
          return const Center(child: Text('No assessments awaiting review.'));
        }
        return ListView.separated(
          padding: const EdgeInsets.all(16),
          itemCount: assessments.length,
          separatorBuilder: (_, _) => const SizedBox(height: 8),
          itemBuilder: (context, index) {
            final assessment = assessments[index];
            return Card(
              child: ListTile(
                leading: const Icon(Icons.science_outlined),
                title: Text(
                  '${assessment.category.name} • ${assessment.recommendation.name}',
                ),
                subtitle: Text(
                  'Item ${assessment.itemId}\nConfidence ${(assessment.confidence * 100).round()}% • SLE ${assessment.recoveryValue.toStringAsFixed(2)}',
                ),
                isThreeLine: true,
                trailing: PopupMenuButton<bool>(
                  onSelected: (approved) => _review(assessment, approved),
                  itemBuilder: (_) => const [
                    PopupMenuItem(value: true, child: Text('Approve')),
                    PopupMenuItem(value: false, child: Text('Reject')),
                  ],
                ),
              ),
            );
          },
        );
      },
    ),
  );
}
